"""الأثرُ المولَّد: ملفٌّ نصيٌّ ببصمته، ومجموعةٌ مرتّبةٌ منها.

    Artifact = (relative_path, text)   ,   digest(Artifact) = digest(bytes(text))

والعرضُ القانونيُّ من عمل المولِّد: UTF-8، وفواصلُ أسطرٍ `\\n`، وسطرٌ أخيرٌ
مُنهًى، وبلا طوابعَ زمنيّة ولا مساراتٍ مطلقةٍ ولا أسماءِ مضيفين؛ فكلُّ واحدٍ من
هذه يجعل بايتاتِ التوليد دالّةً على لحظةِ التشغيل لا على `(Σ_A, g)`.

والمسارُ نسبيٌّ دائمًا: المسارُ المطلق يربط الأثرَ بآلةٍ بعينها، فيكسر
الحتميّةَ عبر الأجهزة بلا أن يُخطئ محلّيًّا.
"""

from __future__ import annotations

from dataclasses import dataclass, fields
from typing import Final

from ..canonical_content import canonical_bytes, canonical_digest

__all__ = [
    "GENERATED_FILE_BANNER",
    "A_GENERATED_FILE_IS_NOT_EDITED_BY_HAND",
    "CANONICAL_RENDERING_IS_THE_GENERATORS_WORK",
    "GeneratedArtifact",
    "GeneratedArtifactError",
    "GeneratedArtifactSet",
]

GENERATED_FILE_BANNER: Final = "# GENERATED BY G_py — DO NOT EDIT BY HAND"

A_GENERATED_FILE_IS_NOT_EDITED_BY_HAND: Final = (
    "الملفُّ المولَّد أثرٌ تنفيذيٌّ مُشتَقّ؛ وتحريرُه يدويًّا يفصله عن "
    "`(Σ_A, g)` فيصير ادّعاءُ التوليد كاذبًا"
)

CANONICAL_RENDERING_IS_THE_GENERATORS_WORK: Final = (
    "العرضُ القانونيُّ من عمل المولِّد لا من عمل مُنسِّقٍ لاحق؛ "
    "و`ruff format --check` فحصٌ بعدُ، لا تعريفٌ للحتميّة"
)

_FORBIDDEN_SUBSTRINGS: Final[tuple[str, ...]] = ("\r", "\t")


class GeneratedArtifactError(ValueError):
    """خطأُ أثرٍ مولَّد: عرضٌ غيرُ قانونيٍّ أو مسارٌ غيرُ نسبيّ."""


def _require_relative_path(value: object) -> str:
    if type(value) is not str or not value.strip():
        raise GeneratedArtifactError("مسارُ الأثر نصٌّ غيرُ فارغ")
    if value.startswith("/") or value.startswith("\\") or ":" in value:
        raise GeneratedArtifactError("مسارُ الأثر نسبيٌّ دائمًا لا مطلق")
    if ".." in value.split("/"):
        raise GeneratedArtifactError("مسارُ الأثر لا يصعد فوق جذر التوليد")
    if value != value.strip():
        raise GeneratedArtifactError("مسارُ الأثر بلا فراغٍ طرفيّ")
    return value


@dataclass(frozen=True, slots=True)
class GeneratedArtifact:
    """ملفٌّ واحدٌ مولَّد: مسارٌ نسبيٌّ ونصٌّ بعرضٍ قانونيّ."""

    relative_path: str
    text: str

    def __post_init__(self) -> None:
        _require_relative_path(self.relative_path)
        if type(self.text) is not str or not self.text:
            raise GeneratedArtifactError("نصُّ الأثر نصٌّ غيرُ فارغ")
        for forbidden in _FORBIDDEN_SUBSTRINGS:
            if forbidden in self.text:
                raise GeneratedArtifactError(
                    f"نصُّ الأثر بلا محارف تحكّمٍ عارضة؛ "
                    f"و{CANONICAL_RENDERING_IS_THE_GENERATORS_WORK}"
                )
        if not self.text.endswith("\n"):
            raise GeneratedArtifactError("نصُّ الأثر يُنهي سطرَه الأخير")
        if self.text.endswith("\n\n"):
            raise GeneratedArtifactError("نصُّ الأثر بلا سطرٍ فارغٍ ختاميّ")
        if GENERATED_FILE_BANNER not in self.text:
            raise GeneratedArtifactError(A_GENERATED_FILE_IS_NOT_EDITED_BY_HAND)

    @property
    def encoded(self) -> bytes:
        """بايتاتُ الأثر بترميز UTF-8."""

        return self.text.encode("utf-8")

    @property
    def content_id(self) -> str:
        """بصمةُ بايتات الأثر."""

        return canonical_digest(self.encoded)

    def as_canonical_content(self) -> dict[str, object]:
        """محتوى الأثر للبصمة: المسارُ وبصمةُ البايتات."""

        return {
            "relative_path": self.relative_path,
            "content_id": self.content_id,
        }


@dataclass(frozen=True, slots=True)
class GeneratedArtifactSet:
    """مجموعةُ آثارٍ مولَّدة، مرتّبةٌ بمساراتها وبلا مسارٍ مكرّر."""

    artifacts: tuple[GeneratedArtifact, ...]

    def __post_init__(self) -> None:
        if not isinstance(self.artifacts, tuple) or not self.artifacts:
            raise GeneratedArtifactError("مجموعةُ الآثار غيرُ فارغة")
        for artifact in self.artifacts:
            if not isinstance(artifact, GeneratedArtifact):
                raise GeneratedArtifactError("عضوُ المجموعة أثرٌ مولَّد")
        paths = tuple(artifact.relative_path for artifact in self.artifacts)
        if len(set(paths)) != len(paths):
            raise GeneratedArtifactError("مسارُ الأثر لا يتكرّر في مجموعةٍ واحدة")
        if paths != tuple(sorted(paths)):
            raise GeneratedArtifactError(
                "آثارُ المجموعة مرتّبةٌ بمساراتها؛ " "وترتيبٌ غيرُ ثابتٍ يكسر الحتميّة"
            )

    @property
    def artifact_paths(self) -> tuple[str, ...]:
        """مساراتُ الآثار مرتّبةً."""

        return tuple(artifact.relative_path for artifact in self.artifacts)

    @property
    def artifact_count(self) -> int:
        """عددُ الآثار، مُشتَقٌّ لا مكتوب."""

        return len(self.artifacts)

    def artifact(self, relative_path: str) -> GeneratedArtifact:
        """أثرٌ بمساره، أو رفضٌ صريحٌ إن لم يكن في المجموعة."""

        for artifact in self.artifacts:
            if artifact.relative_path == relative_path:
                return artifact
        raise GeneratedArtifactError(f"لا أثرَ بالمسار «{relative_path}» في المجموعة")

    def as_canonical_content(self) -> dict[str, object]:
        """محتوى المجموعة للبصمة."""

        return {
            "artifacts": [
                artifact.as_canonical_content() for artifact in self.artifacts
            ]
        }

    @property
    def content_id(self) -> str:
        """بصمةُ مجموعة الآثار."""

        return canonical_digest(canonical_bytes(self.as_canonical_content()))


_JUDGEMENT_FIELD_MARKERS: Final[tuple[str, ...]] = (
    "outcome",
    "verdict",
    "status",
    "standing",
    "birth",
    "proved",
)

for _declaring_type in (
    GeneratedArtifact,
    GeneratedArtifactSet,
):  # pragma: no cover - import guard
    for _field in fields(_declaring_type):
        if any(marker in _field.name for marker in _JUDGEMENT_FIELD_MARKERS):
            raise RuntimeError("الأثرُ المولَّد لا يحمل حكمًا: توليدُ كودٍ ليس إثباتَ نظريّة")
        if any(marker in _field.name for marker in ("count", "coverage", "total")):
            raise RuntimeError("العدُّ مُشتَقٌّ من الآثار لا مكتوبٌ بجانبها")
