"""`G0.RUN-0`: أوّلُ شريحةٍ عموديّةٍ قابلةٍ للتشغيل — محرّكُ ترخيصٍ وتدقيق.

    PK_0 → O_0 → O_L² → ExistenceLineage → Nisbah_v3 → PASS | BLOCK | DEFER

وليس المقصودُ هنا فهمَ جملةٍ عربيّةٍ، بل أن تُعطى القضيّةُ **مُصرَّحًا بعناصرها**
فتُنفَّذ سلسلةُ الترخيص الحقيقيّةُ ويصدر قرارٌ قابلٌ للتدقيق وإعادة التشغيل.

وهذه الطبقةُ **فوق** محور الوجود: تستورد `PK_0` و`O_0` و`O_L²` والسلسلةَ و`v3`،
ولا يستوردها منها شيء؛ فبقاءُ معاني الطبقات السابقة غيرُ متوقّفٍ على وجودها.

تسجيلٌ لا سلطة: لا ولادةَ ولا حكمَ ولادةٍ ولا تجميدَ `E0`.
"""

from __future__ import annotations

from .audit import AN_AUDIT_READS_THE_TRACE_IT_DOES_NOT_JUDGE_AGAIN, audit_lines
from .case_data import (
    A_BASELINE_CHAIN_DOES_NOT_TURN_BACK_ON_ITSELF,
    A_CASE_IS_AUTHORED_NOT_GENERATED,
    A_CITATION_IS_A_CLAIM_UNTIL_THE_READOUT,
    A_DECLARED_DIFFERENCE_IS_THE_ACTUAL_DIFFERENCE,
    A_GOLDEN_COUNTER_CASE_IS_ONE_DECLARED_DIFFERENCE,
    AN_EXPECTATION_CARRIES_NO_EXECUTION_DIGEST,
    AN_INVARIANT_ERROR_IS_NOT_IN_THE_USER_CASE_SPACE,
    CASE_DATA_ID,
    CORPUS_ROOT_NAME,
    CaseDataError,
    CorpusCoverage,
    CoverageCitation,
    DeclaredDifference,
    EngineSeamWitness,
    ExpectedTraceRow,
    GoldenCaseCorpus,
    GoldenExecutionCase,
    GoldenExpectation,
    InvalidInputWitness,
)
from .contract import DecodedDocument, decode_document, encode_declaration
from .coverage import (
    A_LAW_STANDING_IS_NOT_A_CASE_VERDICT,
    A_MATRIX_MEASURES_THE_ENGINE_AS_FROZEN,
    A_MATRIX_NAMES_NO_CASE_AND_NO_DIGEST,
    A_PROHIBITION_IS_READ_IN_ITS_EVALUATION_SCOPE,
    AN_UNREACHABLE_CELL_IS_JUSTIFIED_NOT_INVENTED,
    CASE_EXPECTATION_IS_FROZEN_BEFORE_FIRST_ENGINE_READOUT,
    COVERAGE_MATRIX,
    COVERAGE_MATRIX_DIGEST,
    COVERAGE_MATRIX_ID,
    COVERAGE_REQUIREMENT_IS_FROZEN_BEFORE_CASE_SELECTION,
    EVALUATION_SCOPE_OF_LAW,
    CaseDisposition,
    CoverageAxis,
    CoverageMatrix,
    CoverageMatrixError,
    CoverageRequirement,
    EvaluationScope,
    VerdictEffect,
)
from .declaration import (
    A_DECLARATION_IS_NOT_AN_AUTHORITY,
    EXECUTION_DOCUMENT_SCHEMA,
    JUDGMENT_PRECEDES_CONSTRUCTION,
    AnchorDeclaration,
    CandidateDeclaration,
    CaseDeclaration,
    ConditionSiteDeclaration,
    GeneralOntologyDeclaration,
    LicenseDeclaration,
    LineageDeclaration,
    LinguisticOntologyDeclaration,
    NisbahDeclaration,
    PredicateDeclaration,
    PriorBaseDeclaration,
    PriorConditionDeclaration,
    RoleSiteDeclaration,
    SlotDeclaration,
)
from .derivation import (
    A_DERIVATION_IS_NOT_A_VERDICT,
    DerivedSite,
    PartialAuthorityDerivation,
    RefusalKind,
    SiteKey,
    SiteOwnerKind,
    SiteStanding,
    derive_partial_authority,
)
from .engine import ExecutionReport, execute_declaration, execute_document
from .frozen_json import (
    A_DIFFERENCE_IS_AN_OPERATION_NOT_A_PATH,
    A_FROZEN_DOCUMENT_IS_DEEPLY_IMMUTABLE,
    A_FROZEN_NUMBER_IS_A_JSON_NUMBER,
    A_SEQUENCE_EDIT_WAITS_FOR_ITS_IDENTITY_POLICY,
    DiffOperation,
    FrozenJson,
    FrozenJsonError,
    SequenceIdentityPolicyError,
    StructuralDiff,
    freeze_json,
    frozen_equal,
    structural_diff,
    thaw_json,
)
from .invariant import (
    A_MATERIALIZATION_FAILURE_IS_NOT_A_BLOCK,
    PASS_IFF_MATERIALIZED_IDENTITY,
    ExecutionInvariantError,
)
from .laws import (
    EVERY_LAW_IS_EVALUATED,
    aggregate_outcome,
    evaluate_laws,
    residuals_of,
    violations_of,
)
from .lawset import (
    A_LAW_SET_IS_NOT_REINTERPRETED_BY_A_LATER_ONE,
    DEPENDENT_LAWS,
    LAW_SET,
    LAW_SET_DIGEST,
    LAW_SET_ID,
    ExecutionLaw,
)
from .outcome import (
    A_BLOCKED_DEPENDENT_IS_NOT_MISSING_EVIDENCE,
    NO_CLAIM_IS_NOT_AN_AGREEMENT,
    NO_DEFAULT_SUCCESS_AND_NO_DEFAULT_BLOCK,
    CheckStanding,
    ExecutionOutcome,
    Identity,
    LawCheckEntry,
    Violation,
)
from .replay import SAME_INPUT_SAME_LAWS_SAME_RESULT, is_reproducible, replay
from .requirement import (
    AN_UNRESOLVED_REQUIREMENT_IS_NOT_A_FORGED_REFERENCE,
    UNRESOLVED_EVIDENCE_IS_NOT_INVALID_INPUT,
    RequiredAuthority,
    RequirementStanding,
    UnresolvedRequirement,
)
from .result import (
    A_DIGEST_DOES_NOT_CONTAIN_ITSELF,
    A_REPLAY_NEEDS_THE_DECLARATION_NOT_ITS_DIGEST,
    AN_ENVELOPE_HOLDS_AN_UNALTERABLE_DECLARATION,
    EXECUTION_RESULT_SCHEMA,
    ExecutionResultCore,
    ExecutionResultEnvelope,
    ExecutionResultError,
    LineageIdentity,
)
from .standing import (
    INPUT_CONSTITUTION_FAILURE,
    INVALID_INPUT_IS_NOT_A_BLOCK,
    InputFault,
    InputFaultKind,
    InputStanding,
    InputValidation,
)
from .validation import DeclaredLevels, validate_declaration

__all__ = [
    "AN_AUDIT_READS_THE_TRACE_IT_DOES_NOT_JUDGE_AGAIN",
    "AN_ENVELOPE_HOLDS_AN_UNALTERABLE_DECLARATION",
    "AN_EXPECTATION_CARRIES_NO_EXECUTION_DIGEST",
    "AN_INVARIANT_ERROR_IS_NOT_IN_THE_USER_CASE_SPACE",
    "AN_UNREACHABLE_CELL_IS_JUSTIFIED_NOT_INVENTED",
    "AN_UNRESOLVED_REQUIREMENT_IS_NOT_A_FORGED_REFERENCE",
    "A_BLOCKED_DEPENDENT_IS_NOT_MISSING_EVIDENCE",
    "A_CASE_IS_AUTHORED_NOT_GENERATED",
    "A_CITATION_IS_A_CLAIM_UNTIL_THE_READOUT",
    "A_DECLARATION_IS_NOT_AN_AUTHORITY",
    "A_DERIVATION_IS_NOT_A_VERDICT",
    "A_DIGEST_DOES_NOT_CONTAIN_ITSELF",
    "A_GOLDEN_COUNTER_CASE_IS_ONE_DECLARED_DIFFERENCE",
    "A_LAW_SET_IS_NOT_REINTERPRETED_BY_A_LATER_ONE",
    "A_LAW_STANDING_IS_NOT_A_CASE_VERDICT",
    "A_BASELINE_CHAIN_DOES_NOT_TURN_BACK_ON_ITSELF",
    "A_CONTRACT_BINDS_THE_CLASS_NOT_ITS_FACTORY",
    "A_DECLARED_DIFFERENCE_IS_THE_ACTUAL_DIFFERENCE",
    "A_DIFFERENCE_IS_AN_OPERATION_NOT_A_PATH",
    "A_FROZEN_DOCUMENT_IS_DEEPLY_IMMUTABLE",
    "A_FROZEN_NUMBER_IS_A_JSON_NUMBER",
    "A_MATERIALIZATION_FAILURE_IS_NOT_A_BLOCK",
    "A_MATRIX_MEASURES_THE_ENGINE_AS_FROZEN",
    "A_MATRIX_NAMES_NO_CASE_AND_NO_DIGEST",
    "A_PROHIBITION_IS_READ_IN_ITS_EVALUATION_SCOPE",
    "A_REPLAY_NEEDS_THE_DECLARATION_NOT_ITS_DIGEST",
    "A_SEQUENCE_EDIT_WAITS_FOR_ITS_IDENTITY_POLICY",
    "AnchorDeclaration",
    "CASE_DATA_ID",
    "CASE_EXPECTATION_IS_FROZEN_BEFORE_FIRST_ENGINE_READOUT",
    "CORPUS_ROOT_NAME",
    "COVERAGE_MATRIX",
    "COVERAGE_MATRIX_DIGEST",
    "COVERAGE_MATRIX_ID",
    "COVERAGE_REQUIREMENT_IS_FROZEN_BEFORE_CASE_SELECTION",
    "CandidateDeclaration",
    "CaseDataError",
    "CaseDeclaration",
    "CaseDisposition",
    "CheckStanding",
    "ConditionSiteDeclaration",
    "CorpusCoverage",
    "CoverageAxis",
    "CoverageCitation",
    "CoverageMatrix",
    "CoverageMatrixError",
    "CoverageRequirement",
    "DEPENDENT_LAWS",
    "DeclaredDifference",
    "DiffOperation",
    "DeclaredLevels",
    "DecodedDocument",
    "DerivedSite",
    "EVALUATION_SCOPE_OF_LAW",
    "EVERY_LAW_IS_EVALUATED",
    "EXECUTION_DOCUMENT_SCHEMA",
    "EXECUTION_RESULT_SCHEMA",
    "EngineSeamWitness",
    "EvaluationScope",
    "ExecutionInvariantError",
    "ExecutionLaw",
    "ExecutionOutcome",
    "ExecutionReport",
    "ExecutionResultCore",
    "ExecutionResultEnvelope",
    "ExecutionResultError",
    "ExpectedTraceRow",
    "FrozenJson",
    "FrozenJsonError",
    "GeneralOntologyDeclaration",
    "GoldenCaseCorpus",
    "GoldenExecutionCase",
    "GoldenExpectation",
    "INPUT_CONSTITUTION_FAILURE",
    "INVALID_INPUT_IS_NOT_A_BLOCK",
    "Identity",
    "InputFault",
    "InputFaultKind",
    "InputStanding",
    "InputValidation",
    "InvalidInputWitness",
    "JUDGMENT_PRECEDES_CONSTRUCTION",
    "LAW_SET",
    "LAW_SET_DIGEST",
    "LAW_SET_ID",
    "LawCheckEntry",
    "LicenseDeclaration",
    "LineageDeclaration",
    "LineageIdentity",
    "LinguisticOntologyDeclaration",
    "NO_CLAIM_IS_NOT_AN_AGREEMENT",
    "NO_DEFAULT_SUCCESS_AND_NO_DEFAULT_BLOCK",
    "NisbahDeclaration",
    "PASS_IFF_MATERIALIZED_IDENTITY",
    "PartialAuthorityDerivation",
    "PredicateDeclaration",
    "PriorBaseDeclaration",
    "PriorConditionDeclaration",
    "RefusalKind",
    "RequiredAuthority",
    "RequirementStanding",
    "RoleSiteDeclaration",
    "SAME_INPUT_SAME_LAWS_SAME_RESULT",
    "SequenceIdentityPolicyError",
    "SiteKey",
    "SiteOwnerKind",
    "SiteStanding",
    "SlotDeclaration",
    "StructuralDiff",
    "UNRESOLVED_EVIDENCE_IS_NOT_INVALID_INPUT",
    "UnresolvedRequirement",
    "VerdictEffect",
    "Violation",
    "aggregate_outcome",
    "audit_lines",
    "decode_document",
    "derive_partial_authority",
    "encode_declaration",
    "evaluate_laws",
    "freeze_json",
    "frozen_equal",
    "execute_declaration",
    "execute_document",
    "is_reproducible",
    "replay",
    "residuals_of",
    "structural_diff",
    "thaw_json",
    "validate_declaration",
    "violations_of",
]
