"""`G0.GEN-0.SPEC`: مواصفةُ الإنتاج العربيِّ المرخَّص، قبل أن يُنتَج حرفٌ واحد.

    Surface  --Analysis-->  LicensedStructure
    LicensedStructure  --Generation-->  Surface

    Analysis ≠ Generation⁻¹

وهذه الطبقةُ **فوق** محرّك التنفيذ: تقرأ `execution/` شهادةَ نجاحٍ سابقةً، ولا
يستوردها منها شيء. ولا تُشغِّل المحرّك، ولا تفتح `Agent`/`Patient` في
`linguistic/nisbah.py`، ولا تكتب صورةً سطحيّةً في مواصفة.

والعائلةُ المفتوحةُ واحدةٌ: `PastActiveTransitiveVSO` — فعلٌ ماضٍ معلومٌ بصيغةٍ
معجميّةٍ مشهودةٍ لا مشتقّةٍ من جذر، وفاعلٌ مفردٌ ظاهر، ومفعولٌ به مفردٌ ظاهر،
بترتيب `VSO` وحده.

تسجيلٌ لا سلطة: لا ولادةَ، ولا حكمَ ولادةٍ، ولا تجميدَ `E0`.
"""

from __future__ import annotations

from .authority_gaps import (
    GENERATION_AUTHORITY_GAPS,
    NO_INDEPENDENT_ANCHOR_TO_SYNTACTIC_FUNCTION_AUTHORITY,
    NO_VERIFIED_LEXICAL_ATTESTATION,
    GenerationAuthorityGap,
    GenerationAuthorityGapError,
)
from .candidate import (
    DO_NOT_STORE_DERIVABLE_IDENTITY_AS_A_SECOND_CLAIM,
    PHONOLOGICAL_PROJECTION_IS_WITHHELD_IN_GEN0,
    CaseEffectCandidate,
    CompositionCandidate,
    GeneratedArabicUtterance,
    GeneratedStage,
    GenerationCandidateError,
    LexicalSelectionCandidate,
    MorphologicalOperation,
    OrthographicProjection,
    RelationSlotAssignment,
    StageReadout,
    SurfaceToken,
    WithheldStage,
    WordFormCandidate,
    specification_content_id,
    withheld_phonological_projection,
)
from .certificate import (
    CONFORMANCE_AUTHORITY_GAPS,
    GEN0_PRESERVED_INVARIANTS,
    ROUND_TRIP_IS_SPECIFIED_NOT_ISSUABLE,
    CertifiedGeneratedUtterance,
    GenerationRankError,
    PreservedGenerationInvariant,
    PreservedInvariantSpec,
    RoundTripCertificate,
    RoundTripDecision,
    RoundTripGate,
    RoundTripStatus,
    SpecificationConformanceDecision,
    SpecificationConformanceGate,
    SpecificationConformanceStatus,
    SpecificationConformantSurface,
    SurfaceCandidate,
)
from .laws import (
    A_POSITION_IS_NOT_A_SEMANTIC_ROLE,
    AN_UNREALIZED_LAYER_IS_A_WITHHELD_STAGE_NOT_A_NULL,
    ANALYSIS_IS_NOT_INVERTED_GENERATION,
    CALLER_DOES_NOT_OWN_GENERATION_RANK,
    CONFORMANCE_IS_NOT_LICENSING,
    CONTRACT_MUST_BIND_CLASS_NOT_FACTORY,
    GENERATION_DOES_NOT_INVENT_INTENT,
    GENERATION_LAW_SET_DIGEST,
    GENERATION_LAW_SET_ID,
    GENERATION_LAWS,
    GENERATION_SPEC_H_LAW_SET_DIGEST,
    GENERATION_SPEC_H_LAW_SET_ID,
    GENERATION_SPEC_H_LAWS,
    LEXICAL_CHOICE_REF_IS_A_CLAIM_UNTIL_THE_READOUT,
    NO_CERTIFIED_GENERATION_WITHOUT_ROUND_TRIP,
    NO_COMPOSITION_WITHOUT_RELATION,
    NO_GENERATION_AUTHORITY_BEYOND_ITS_SOURCE,
    NO_INFLECTION_WITHOUT_LICENSED_SLOT,
    NO_LEXEME_OUTSIDE_A_FROZEN_LEXICAL_SOURCE,
    NO_SURFACE_WITHOUT_SOURCE_ANCHOR,
    NO_WORD_FORM_WITHOUT_MORPHOLOGICAL_TRACE,
    ORTHOGRAPHY_NEED_NOT_CLAIM_PHONOLOGICAL_DERIVATION,
    RESIDUALS_ARE_OBSERVED_NOT_AUTHORED,
)
from .specification import (
    PAST_ACTIVE_TRANSITIVE_VSO,
    CaseEffect,
    FormSelectionMode,
    GenerationSpecificationError,
    LexicalChoiceRef,
    PassedNisbahSourceRef,
    ProductionFamily,
    ProductionFamilySpec,
    ProductionSpecification,
    RealizationConstraint,
    RealizationConstraintKind,
    RealizationConstraintValue,
    RealizationTargetAssignment,
    RequestedSentenceForm,
    RequestedTense,
    RequestedVoice,
    SourceElementKind,
    SourceElementRef,
    SourceInventorySnapshot,
    SyntacticRealizationTarget,
)
from .trace import (
    A_CHAIN_IS_READ_FROM_ITS_DIGESTS_NOT_ITS_ORDER,
    SAME_SPECIFICATION_SAME_RULES_SAME_TRACE,
    GenerationResidual,
    GenerationResidualKind,
    GenerationStage,
    GenerationStep,
    GenerationTrace,
    GenerationTraceError,
)

__all__ = [
    "ANALYSIS_IS_NOT_INVERTED_GENERATION",
    "AN_UNREALIZED_LAYER_IS_A_WITHHELD_STAGE_NOT_A_NULL",
    "A_CHAIN_IS_READ_FROM_ITS_DIGESTS_NOT_ITS_ORDER",
    "A_POSITION_IS_NOT_A_SEMANTIC_ROLE",
    "CALLER_DOES_NOT_OWN_GENERATION_RANK",
    "CONFORMANCE_IS_NOT_LICENSING",
    "CONFORMANCE_AUTHORITY_GAPS",
    "CONTRACT_MUST_BIND_CLASS_NOT_FACTORY",
    "CaseEffect",
    "CaseEffectCandidate",
    "CertifiedGeneratedUtterance",
    "CompositionCandidate",
    "FormSelectionMode",
    "GEN0_PRESERVED_INVARIANTS",
    "GENERATION_DOES_NOT_INVENT_INTENT",
    "GENERATION_AUTHORITY_GAPS",
    "GENERATION_LAWS",
    "GENERATION_LAW_SET_DIGEST",
    "GENERATION_LAW_SET_ID",
    "GENERATION_SPEC_H_LAWS",
    "GENERATION_SPEC_H_LAW_SET_DIGEST",
    "GENERATION_SPEC_H_LAW_SET_ID",
    "GeneratedArabicUtterance",
    "GeneratedStage",
    "DO_NOT_STORE_DERIVABLE_IDENTITY_AS_A_SECOND_CLAIM",
    "GenerationAuthorityGap",
    "GenerationAuthorityGapError",
    "GenerationCandidateError",
    "GenerationRankError",
    "GenerationResidual",
    "GenerationResidualKind",
    "GenerationSpecificationError",
    "GenerationStage",
    "GenerationStep",
    "GenerationTrace",
    "GenerationTraceError",
    "LEXICAL_CHOICE_REF_IS_A_CLAIM_UNTIL_THE_READOUT",
    "LexicalChoiceRef",
    "LexicalSelectionCandidate",
    "MorphologicalOperation",
    "NO_CERTIFIED_GENERATION_WITHOUT_ROUND_TRIP",
    "NO_COMPOSITION_WITHOUT_RELATION",
    "NO_GENERATION_AUTHORITY_BEYOND_ITS_SOURCE",
    "NO_INDEPENDENT_ANCHOR_TO_SYNTACTIC_FUNCTION_AUTHORITY",
    "NO_VERIFIED_LEXICAL_ATTESTATION",
    "NO_INFLECTION_WITHOUT_LICENSED_SLOT",
    "NO_LEXEME_OUTSIDE_A_FROZEN_LEXICAL_SOURCE",
    "NO_SURFACE_WITHOUT_SOURCE_ANCHOR",
    "NO_WORD_FORM_WITHOUT_MORPHOLOGICAL_TRACE",
    "ORTHOGRAPHY_NEED_NOT_CLAIM_PHONOLOGICAL_DERIVATION",
    "OrthographicProjection",
    "PAST_ACTIVE_TRANSITIVE_VSO",
    "PHONOLOGICAL_PROJECTION_IS_WITHHELD_IN_GEN0",
    "PassedNisbahSourceRef",
    "PreservedGenerationInvariant",
    "PreservedInvariantSpec",
    "ProductionFamily",
    "ProductionFamilySpec",
    "ProductionSpecification",
    "RESIDUALS_ARE_OBSERVED_NOT_AUTHORED",
    "ROUND_TRIP_IS_SPECIFIED_NOT_ISSUABLE",
    "RealizationConstraint",
    "RealizationConstraintKind",
    "RealizationConstraintValue",
    "RealizationTargetAssignment",
    "RelationSlotAssignment",
    "RequestedSentenceForm",
    "RequestedTense",
    "RequestedVoice",
    "RoundTripCertificate",
    "RoundTripDecision",
    "RoundTripGate",
    "RoundTripStatus",
    "SAME_SPECIFICATION_SAME_RULES_SAME_TRACE",
    "SourceElementKind",
    "SourceElementRef",
    "SourceInventorySnapshot",
    "StageReadout",
    "SpecificationConformanceDecision",
    "SpecificationConformanceGate",
    "SpecificationConformanceStatus",
    "SpecificationConformantSurface",
    "SurfaceCandidate",
    "SurfaceToken",
    "SyntacticRealizationTarget",
    "WithheldStage",
    "WordFormCandidate",
    "specification_content_id",
    "withheld_phonological_projection",
]
