import A116

/-!
تدقيقُ المسلّمات: لا يُقبَل برهانٌ يستند إلى `sorryAx` أو إلى مسلّمةٍ غيرِ
المسلّمات القياسيّة في Lean (`propext`، `Classical.choice`، `Quot.sound`).
ويفحص CI هذا المخرَج ويسقط إن ظهر فيه `sorryAx` أو `Lean.ofReduceBool`
(أثرُ `native_decide`، وهو ثقةٌ بالمترجِم لا بالنواة).
-/

#print axioms A116.mem_cells
#print axioms A116.cells_nodup
#print axioms A116.cells_length
#print axioms A116.cells_split
#print axioms A116.step_depends_only_on_sukun
#print axioms A116.run_fellOut
#print axioms A116.saturation_rungs
#print axioms A116.Sstar_closed
#print axioms A116.run_mem_Sstar
#print axioms A116.Sstar_complete
#print axioms A116.run_ne_fellOut_iff
#print axioms A116.run_eq_fellOut_iff
#print axioms A116.Fold.T_succ_succ
#print axioms A116.Fold.fold_lt
#print axioms A116.Fold.unfold_fold
#print axioms A116.Fold.unfold_spec
#print axioms A116.Fold.fold_injective
#print axioms A116.Fold.foldAny_injective
#print axioms A116.Fold.foldAny_surjective
#print axioms A116.admissible_iff_valid
#print axioms A116.run_ne_fellOut_iff_valid
#print axioms A116.cellFold_lt
#print axioms A116.cellFold_injective
#print axioms A116.cellFold_surjective
#print axioms A116.U_succ_succ
#print axioms A116.U_values
#print axioms A116.hamil_ladder
#print axioms A116.Fiber.decode_encode
#print axioms A116.Fiber.encode_injective
#print axioms A116.Fiber.decode_sound
#print axioms A116.Fiber.rank_lt
#print axioms A116.Fiber.fiber_length_le
#print axioms A116.Fiber.fiber_length_le_two_pow
#print axioms A116.Fiber.nodup_fin_length_le
#print axioms A116.Numbering.valid_zero_iff
#print axioms A116.Numbering.fold_zero_eq_digits
#print axioms A116.Numbering.foldAny_zero_closed
#print axioms A116.Numbering.bridgeCell_bridgeIndex
#print axioms A116.Numbering.bridgeIndex_bridgeCell
#print axioms A116.Numbering.orders_differ_only_in_two_rows
#print axioms A116.Numbering.atomNumber_closed
#print axioms A116.Numbering.atomNumber_injective
#print axioms A116.Numbering.atomNumber_surjective
#print axioms A116.Numbering.pair_injective
#print axioms A116.Numbering.pair_surjective
#print axioms A116.Numbering.pair_closed
#print axioms A116.Ishtiqaq.extract_fill_wf
#print axioms A116.Ishtiqaq.root_sublist_fill_wf
#print axioms A116.Ishtiqaq.fill_injective
#print axioms A116.Ishtiqaq.soundTemplates_wf
#print axioms A116.Ishtiqaq.form_alone_does_not_determine_root
#print axioms A116.Field112.field112_eq_cells112
#print axioms A116.Field112.hamzaRow_named
#print axioms A116.Field112.cells_eq_field112_append_hamza
#print axioms A116.Derivation.branching_nodes
#print axioms A116.Derivation.rows_stochastic
#print axioms A116.Derivation.stationary_unique
#print axioms A116.Derivation.share_of_I
#print axioms A116.Derivation.stationary_w
#print axioms A116.Ladder.run_depends_only_on_pattern
#print axioms A116.Ladder.U_eq_pow_mul_g
#print axioms A116.Ladder.pattern_count_fib
#print axioms A116.Ladder.admissible_patterns_3
#print axioms A116.Ladder.U3_by_pattern
#print axioms A116.Ladder.patterns_of_the_cited_words
#print axioms A116.Ladder.kana_and_inna_are_indistinguishable
#print axioms A116.Ladder.kana_is_not_kataba
#print axioms A116.Stages.parse_flat
#print axioms A116.Stages.flat_parse
#print axioms A116.Stages.flat_injective
#print axioms A116.Junction.admissible_map_carriers
#print axioms A116.Junction.admissible_prefix
#print axioms A116.Junction.admissible_append
#print axioms A116.Junction.U_by_patterns_upto_6
#print axioms A116.Junction.licensed_upto_4
#print axioms A116.Junction.burnside_3
#print axioms A116.Junction.burnside_4
#print axioms A116.Pause.mem_pats_iff
#print axioms A116.Pause.U_by_patterns
#print axioms A116.Pause.pause_admissible
#print axioms A116.Pause.pause_strictly_extends
#print axioms A116.Ternary.binary_is_continue
#print axioms A116.Ternary.continue_strictly_extends_binary
#print axioms A116.Ternary.continue_is_pause
#print axioms A116.Ternary.pause_strictly_extends_continue
#print axioms A116.Ternary.tamm_is_pause_only
#print axioms A116.Ternary.binary_is_blind_to_madd
#print axioms A116.Ternary.admissible_iff_admissibleB
#print axioms A116.Ternary.binOK_eq_admissibleB
#print axioms A116.Ternary.continueB_iff
#print axioms A116.Ternary.pauseB_iff
#print axioms A116.Recovery.edit_roundtrip
#print axioms A116.Recovery.shadda_restore
#print axioms A116.Recovery.tanwin_restore
#print axioms A116.Recovery.hamza_restore
#print axioms A116.Recovery.ilal_edit_restore
#print axioms A116.Recovery.no_seat_recovery_from_hamza_alone
#print axioms A116.Recovery.restoration_forces_fiber_separation
#print axioms A116.Recovery.compose_restoration
#print axioms A116.Residue.sukun_restore
#print axioms A116.Residue.fariqa_restore
#print axioms A116.Residue.tanwinAlif_restore
#print axioms A116.Residue.idgham_restore
#print axioms A116.Residue.daggerAlif_restore
#print axioms A116.Residue.chain_restore
#print axioms A116.Residue.residue_separates
#print axioms A116.Unicode.decode_encode
#print axioms A116.Unicode.encode_prefix_free
#print axioms A116.Unicode.decodeAll_encodeAll
#print axioms A116.Unicode.arabic_is_two_bytes
#print axioms A116.Unicode.markOrder_restore
#print axioms A116.Boundary.no_start_with_sukun
#print axioms A116.Boundary.pause_ends_with_sukun
#print axioms A116.Boundary.join_iff
#print axioms A116.Boundary.wasl_dropped_needs_moving_left
#print axioms A116.Boundary.pause_then_join_is_not_join
#print axioms A116.Ilal.admissible_replace_carrier
#print axioms A116.Ilal.vowelled_to_sukun_between_vowelled
#print axioms A116.Ilal.swap_sukun_vowel
#print axioms A116.Ilal.delete_sukun_after_vowelled
#print axioms A116.Ilal.two_sukun_not_admissible
#print axioms A116.Ilal.hadhf_ayn_forced
#print axioms A116.Ilal.qalb_ayn_restore
#print axioms A116.Ilal.naql_restore
#print axioms A116.Ilal.ibdal_restore
#print axioms A116.Ilal.qala_witness
#print axioms A116.Ilal.qultu_witness
#print axioms A116.Ilal.yaqulu_witness
#print axioms A116.Hamza.seat_initial_by_own
#print axioms A116.Hamza.seat_final_by_prev
#print axioms A116.Hamza.seat_after_madd_final_is_line
#print axioms A116.Hamza.seat_medial_strongest
#print axioms A116.Hamza.seat_depends_on_context
#print axioms A116.Hamza.qat_stays_when_joined
#print axioms A116.Hamza.prefix_hamza_admissible
#print axioms A116.Hadd.strictB_continue
#print axioms A116.Hadd.geminateB_vc_carrier
#print axioms A116.Hadd.geminateB_vc_final
#print axioms A116.Hadd.strict_cvvc_is_geminate
#print axioms A116.Hadd.kindOf_hajja
#print axioms A116.Hadd.continueB_flat
#print axioms A116.Hadd.hadd_debt_closed
#print axioms A116.Hadd.hajja_strict
#print axioms A116.Hadd.dallina_strict
#print axioms A116.Hadd.qultu_strict
#print axioms A116.Hadd.alaana_strict
#print axioms A116.Hadd.farq_needs_its_hamza
#print axioms A116.Hadd.strictJoinB_strict
#print axioms A116.Hadd.strictJoinB_nil
#print axioms A116.Hadd.straddle_rejected
#print axioms A116.Hadd.ya_shafiina_straddles
#print axioms A116.Hadd.quli_dallina_join
#print axioms A116.Hadd.quli_lhamdu_join
