import Slge.Categories

/-! سجلُّ الانتقالات (‎Word → Word‎) في `src/slge` بأسماء مبرهناتها المدقَّقة — مولَّدٌ بـ
`tools/gen_intiqal_index.py` من `slge.intiqal.REGISTRY` بعد فحص الشجرة و`Audit.lean`؛
لا يُحرَّر باليد. الصفُّ: (الوحدة، الدالّة، المبرهنة أو فارغ، نوعُها: 0 إغلاق / 1 خاصّة / 2 دَين).
-/

namespace Slge.IntiqalTable

def registry : List (String × String × String × Nat) := [
  ("adad", "masc", "Slge.Adad.genderOf_masc", 1),
  ("adad", "fem", "Slge.Adad.genderOf_fem_forms", 1),
  ("adad", "compound", "Slge.Adad.compound_both_fatha", 1),
  ("adad", "uqud", "Slge.Adad.uqud_case", 1),
  ("adawat", "apply", "Slge.Adawat.apply_licensed", 0),
  ("damair", "attach", "Slge.Damair.attach_licensed", 0),
  ("fil", "qalb", "Slge.Fil.qalb_licensed", 0),
  ("fil", "naql", "Slge.Fil.naql_licensed", 0),
  ("fil", "ibdal", "Slge.Fil.ibdal_licensed", 0),
  ("fil", "idgham", "Slge.Fil.idgham_licensed", 0),
  ("filiyya", "past", "Slge.Filiyya.past_licensed", 0),
  ("filiyya", "fail", "Slge.Filiyya.fail_reads_raf", 1),
  ("filiyya", "majhul", "Slge.Filiyya.majhul_fill", 1),
  ("filiyya", "majhul_pres", "", 2),
  ("filiyya", "naib", "Slge.Filiyya.naib_eq_fail", 1),
  ("filiyya", "maful", "Slge.Filiyya.maful_reads_nasb", 1),
  ("filiyya", "maiyya", "Slge.Filiyya.maiyya_licensed", 0),
  ("ilal", "restore", "Slge.Ilal.apply_roundtrip", 0),
  ("ishara", "tanbih", "Slge.Ishara.tanbih_licensed", 0),
  ("ishara", "bud", "Slge.Ishara.bud_licensed", 0),
  ("ishara", "dual", "Slge.Ishara.caseOf_dual", 1),
  ("ism", "nisba", "Slge.Ism.nisba_licensed", 0),
  ("ism", "prepare", "", 2),
  ("istifham", "idgham_nm", "Slge.Istifham.idghamNM_length", 1),
  ("istifham", "ma_after_jarr", "Slge.Istifham.ma_after_jarr", 1),
  ("jazm", "sukun", "Slge.Jazm.sukun_licensed", 0),
  ("jazm", "drop_weak", "Slge.Jazm.dropWeak_licensed", 0),
  ("jazm", "amr", "Slge.Jazm.amr_licensed", 0),
  ("jidh", "stem_form", "Slge.Jidh.stemSenses_eq_stemForm", 1),
  ("jumla", "lam", "Slge.Jumla.lam_licensed", 0),
  ("jumla", "ta_nith", "Slge.Jumla.gender_taNith", 1),
  ("jumla", "dual", "", 2),
  ("jumla", "jam_m", "", 2),
  ("jumla", "jam_f", "Slge.Jumla.gender_jamF", 1),
  ("jumla", "bare", "", 2),
  ("majrurat", "jarr", "Slge.Majrurat.jarr_licensed", 0),
  ("majrurat", "jarr_nakira", "", 2),
  ("majrurat", "dual", "Slge.Majrurat.dual_jarr_compatible", 1),
  ("majrurat", "mudaf", "Slge.Majrurat.mudaf_no_tanwin", 1),
  ("majrurat", "mudaf_uqud", "", 2),
  ("majrurat", "mudaf_dual", "", 2),
  ("mansubat", "raf", "", 2),
  ("mansubat", "nasb", "Slge.Mansubat.nakira_reads_nasb", 1),
  ("mansubat", "nakira_mansuba", "", 2),
  ("mansubat", "strip_suffix", "", 2),
  ("mansubat", "fakk", "", 2),
  ("mansubat", "mustathna", "", 2),
  ("mansubat", "ghayr_of", "", 2),
  ("mansubat", "after_khala", "Slge.Mansubat.ma_khala_nasb", 1),
  ("maqam", "with_prefix", "Slge.Maqam.withPrefix_fill", 1),
  ("marifa", "shamsi", "Slge.Marifa.shamsi_licensed", 0),
  ("marifa", "al", "Slge.Marifa.al_licensed", 0),
  ("marifa", "drop_tanwin", "Slge.Marifa.dropTanwin_licensed", 0),
  ("marifa", "idafa", "Slge.Marifa.idafa_no_tanwin", 1),
  ("naat", "naat", "Slge.Naat.naatOk_agree", 1),
  ("nawasikh", "raf", "Slge.Nawasikh.raf_licensed", 0),
  ("nawasikh", "nasb", "Slge.Nawasikh.nasb_licensed", 0),
  ("nawasikh", "tanwin", "Slge.Nawasikh.no_tanwin_setLast", 1),
  ("nawasikh", "kaffa", "Slge.Nawasikh.kaffa_licensed", 0),
  ("nida", "ya_junction", "Slge.Nida.ya_junction", 1),
  ("nida", "nudba", "Slge.Nida.nudba_not_binary_licensed", 0),
  ("nisab", "isnad", "Slge.Nisab.isnad_one_operation", 1),
  ("sarf", "sarf_jarr", "Slge.Sarf.sarf_jarr_ne_nasb", 1),
  ("sarf", "sarf_nasb", "", 2),
  ("sarf", "mamnu_jarr", "Slge.Alam.mamnu_jarr_is_fatha", 1),
  ("sarf", "al_jarr", "Slge.Sarf.al_jarr_kasra", 1),
  ("sarf", "idafa_jarr", "Slge.Sarf.idafa_jarr_kasra", 1),
  ("sawabiq", "lift", "Slge.Sawabiq.joined_is_initial", 1),
  ("sawabiq", "lift_arid", "Slge.Sawabiq.liftArid_tail", 1),
  ("shibh", "jarr_majrur", "Slge.Shibh.jarr_majrur_licensed", 0),
  ("siyaq", "project", "Slge.Siyaq.project_restore", 0),
  ("siyaq", "waqf", "Slge.Siyaq.waqf_candidates_sound", 0),
  ("shibh", "zarf", "", 2),
  ("talab", "lam_amr", "Slge.Talab.lam_amr_licensed", 0),
  ("talab", "lam_amr_after_waw", "Slge.Sawabiq.sakin_is_kasra", 1),
  ("talab", "masdar_amr", "", 2),
  ("talil", "maful_li_ajlih", "", 2),
  ("talil", "apply", "", 2),
  ("tawabi", "tawkid", "Slge.Tawabi.tawkid_words_licensed", 0),
  ("tawzi", "alif_to_ya", "", 2),
  ("wasl", "drop_wasl", "Slge.Wasl.wasl_drops", 0),
  ("wasl", "istifham_verb", "Slge.Wasl.istifhamVerb_licensed", 0),
  ("zaman", "raf_tanwin", "Slge.Zaman.hukm_rafTanwin", 1),
  ("zaman", "nasb_tanwin", "Slge.Zaman.hukm_nasbTanwin", 1),
  ("zawaid", "tawkid", "Slge.Zawaid.tawkid_licensed", 0),
  ("zawaid", "anith", "Slge.Zawaid.anith_licensed", 0),
  ("zuruf", "set_last", "Slge.Zuruf.setLast_licensed", 0),
  ("zuruf", "mudaf", "Slge.Zuruf.hukm_mudaf", 1),
  ("zuruf", "jarr", "Slge.Zuruf.hukm_jarr", 1),
  ("zuruf", "qat", "Slge.Zuruf.hukm_qat", 1)
]

theorem registry_length : registry.length = 90 := by rfl

end Slge.IntiqalTable
