"""`G0.METRIC-0` — خريطةُ القدرات العربية الكسريّة.

المقامُ `DeclaredArabicCapabilityUniverseV1` مُعلَنٌ من خارج التنفيذ، والقدرةُ
غيرُ المبنيّة تبقى فيه صفًّا ظاهرًا بحالة `S0_ABSENT` ومانِعِها وبوّابتها
التالية. والشواهدُ تدخل بمسارات سلطةٍ مُنمَّطة، والشهادةُ تُشتَقّ بالكامل ولا
يُملأ فيها حقلٌ يدويًّا.

ولا سلطةَ لهذه الحزمة: لا تقرؤها بوّابةٌ في `kernel/`، ولا تُولِد ولا تُجمِّد.
"""

from __future__ import annotations

from .aggregate import (
    COVERAGE_GEOMETRY,
    AggregationError,
    DerivedRatio,
    DomainCoverageProfile,
    DomainCoverageRow,
    NodeAggregate,
    aggregate_universe,
    derive_domain_coverage_profile,
)
from .audit import (
    CAPABILITY_FORBIDDEN_PACKAGES,
    CAPABILITY_IMPORT_POLICY,
    CAPABILITY_PERMITTED_MODULES,
    capability_import_isolation_audit,
)
from .blockers import BlockerRow, rank_blockers
from .certificate import (
    CERTIFICATE_SCHEMA_VERSION,
    COVERAGE_INDICATOR_NAMES,
    ArabicStateCertificate,
    CertificateNodeRow,
    derive_arabic_state_certificate,
)
from .declaration import (
    DECLARATION_PROTOCOL_ID,
    declaration_protocol_digest,
    derive_declaration_evidence,
)
from .evidence import (
    AuthorityPath,
    EvidenceError,
    EvidenceLedger,
    EvidencePolarity,
    EvidenceRefusal,
    EvidenceScope,
    RefusalCode,
    ResidualDisclosure,
    ScopedCapabilityEvidence,
    licensable_gates,
)
from .governance import GovernanceIndicators, derive_governance_indicators
from .laws import (
    A_DECLARED_DENOMINATOR_IS_NOT_THE_COMPLETE_ONTOLOGY_OF_ARABIC,
    A_DENOMINATOR_DERIVED_FROM_THE_IMPLEMENTATION_IS_NOT_A_MEASURE,
    A_RATIO_CARRIES_ITS_DENOMINATOR,
    BREADTH_IS_NOT_READINESS,
    CAPABILITY_LAWS,
    CITATION_NAME_IS_NOT_A_VERIFIED_SOURCE_LOCUS,
    DECLARED_COVERAGE_IS_NOT_SYSTEM_CAPABILITY,
    DIFFERENT_MEASUREMENT_SEMANTICS_ARE_NOT_COMPARABLE_CERTIFICATES,
    EQUAL_DOMAIN_WEIGHTING_IS_STILL_A_WEIGHTING_PROTOCOL,
    EVIDENCE_MUST_HAVE_AN_AUTHORITY_PATH,
    KEEPING_A_QUESTION_DOES_NOT_LICENSE_A_FALSE_CITATION,
    MISSING_IMPLEMENTATION_DOES_NOT_REMOVE_A_CAPABILITY,
    NO_KERNEL_MODULE_CONSUMES_THE_CAPABILITY_MAP,
    NO_ORDINAL_GATE_ARITHMETIC_WITHOUT_DECLARED_WEIGHTS,
    OUR_CONCEPTUAL_MAPPING_IS_NOT_A_SOURCE_TEXT_ANCHOR,
    REPEATED_REFERENCE_IS_NOT_INDEPENDENT_EVIDENCE,
    SOURCE_CITATION_DOES_NOT_LICENSE_SYSTEM_CAPABILITY,
    STANDINGS_ARE_GATES_NOT_EPISTEMIC_MAGNITUDES,
    TAXONOMY_GRANULARITY_IS_NOT_CAPABILITY_IMPORTANCE,
    THE_DENOMINATOR_IS_CITED_NOT_INVENTED,
    THE_METRIC_MUST_BE_ALLOWED_TO_GO_DOWN,
    UNIFORM_READINESS_GATE_IS_NOT_A_DERIVED_READINESS_REQUIREMENT,
    UNIMPLEMENTED_CAPABILITY_MUST_REMAIN_VISIBLE,
)
from .maturity import GATE_SEQUENCE, MaturityStage, blocking_reason_for_gate
from .measure import LeafMeasurement, measure_leaves
from .node import (
    CITATION_STANDING_SEQUENCE,
    DECLARED_EDITIONS,
    DECLARED_SOURCES,
    CapabilityCitation,
    CapabilityNode,
    CapabilityNodeError,
    CitationStanding,
    DeclaredEdition,
    DeclaredSource,
    NodeKind,
    ReadinessGateOrigin,
    Requirement,
)
from .provenance import (
    CitationProvenanceProfile,
    ReadinessGateOriginProfile,
    derive_citation_provenance_profile,
    derive_readiness_gate_origin_profile,
)
from .universe import CapabilityUniverse, CapabilityUniverseError, UniverseManifest
from .universe_v1 import (
    ARABIC_TOTAL_ID,
    DECLARED_ARABIC_CAPABILITY_UNIVERSE_V1,
    DECLARED_READINESS_GATE,
    DECLARED_READINESS_GATE_ORIGIN,
    UNIVERSE_V1_ID,
    build_declared_universe_v1,
)
from .weights import (
    ATTESTABLE_GATES,
    DeclaredScalar,
    GateWeight,
    MeasurementSemanticsError,
    MeasurementWeightProtocol,
    ScalarStanding,
    UndeclaredScalar,
    UndeclaredScalarReason,
    derive_composite_coverage,
)

__all__ = [
    "ARABIC_TOTAL_ID",
    "ATTESTABLE_GATES",
    "A_DECLARED_DENOMINATOR_IS_NOT_THE_COMPLETE_ONTOLOGY_OF_ARABIC",
    "A_DENOMINATOR_DERIVED_FROM_THE_IMPLEMENTATION_IS_NOT_A_MEASURE",
    "A_RATIO_CARRIES_ITS_DENOMINATOR",
    "AggregationError",
    "ArabicStateCertificate",
    "AuthorityPath",
    "BREADTH_IS_NOT_READINESS",
    "BlockerRow",
    "CAPABILITY_FORBIDDEN_PACKAGES",
    "CAPABILITY_IMPORT_POLICY",
    "CAPABILITY_LAWS",
    "CAPABILITY_PERMITTED_MODULES",
    "CERTIFICATE_SCHEMA_VERSION",
    "CITATION_NAME_IS_NOT_A_VERIFIED_SOURCE_LOCUS",
    "CITATION_STANDING_SEQUENCE",
    "COVERAGE_GEOMETRY",
    "COVERAGE_INDICATOR_NAMES",
    "CapabilityCitation",
    "CapabilityNode",
    "CapabilityNodeError",
    "CapabilityUniverse",
    "CapabilityUniverseError",
    "CertificateNodeRow",
    "CitationProvenanceProfile",
    "CitationStanding",
    "DECLARATION_PROTOCOL_ID",
    "DECLARED_ARABIC_CAPABILITY_UNIVERSE_V1",
    "DECLARED_COVERAGE_IS_NOT_SYSTEM_CAPABILITY",
    "DECLARED_EDITIONS",
    "DECLARED_READINESS_GATE",
    "DECLARED_READINESS_GATE_ORIGIN",
    "DECLARED_SOURCES",
    "DIFFERENT_MEASUREMENT_SEMANTICS_ARE_NOT_COMPARABLE_CERTIFICATES",
    "DeclaredEdition",
    "DeclaredScalar",
    "DeclaredSource",
    "DerivedRatio",
    "DomainCoverageProfile",
    "DomainCoverageRow",
    "EQUAL_DOMAIN_WEIGHTING_IS_STILL_A_WEIGHTING_PROTOCOL",
    "EVIDENCE_MUST_HAVE_AN_AUTHORITY_PATH",
    "EvidenceError",
    "EvidenceLedger",
    "EvidencePolarity",
    "EvidenceRefusal",
    "EvidenceScope",
    "GATE_SEQUENCE",
    "GateWeight",
    "GovernanceIndicators",
    "KEEPING_A_QUESTION_DOES_NOT_LICENSE_A_FALSE_CITATION",
    "LeafMeasurement",
    "MISSING_IMPLEMENTATION_DOES_NOT_REMOVE_A_CAPABILITY",
    "MaturityStage",
    "MeasurementSemanticsError",
    "MeasurementWeightProtocol",
    "NO_KERNEL_MODULE_CONSUMES_THE_CAPABILITY_MAP",
    "NO_ORDINAL_GATE_ARITHMETIC_WITHOUT_DECLARED_WEIGHTS",
    "NodeAggregate",
    "NodeKind",
    "OUR_CONCEPTUAL_MAPPING_IS_NOT_A_SOURCE_TEXT_ANCHOR",
    "REPEATED_REFERENCE_IS_NOT_INDEPENDENT_EVIDENCE",
    "ReadinessGateOrigin",
    "ReadinessGateOriginProfile",
    "RefusalCode",
    "Requirement",
    "ResidualDisclosure",
    "SOURCE_CITATION_DOES_NOT_LICENSE_SYSTEM_CAPABILITY",
    "STANDINGS_ARE_GATES_NOT_EPISTEMIC_MAGNITUDES",
    "ScalarStanding",
    "ScopedCapabilityEvidence",
    "TAXONOMY_GRANULARITY_IS_NOT_CAPABILITY_IMPORTANCE",
    "THE_DENOMINATOR_IS_CITED_NOT_INVENTED",
    "THE_METRIC_MUST_BE_ALLOWED_TO_GO_DOWN",
    "UNIFORM_READINESS_GATE_IS_NOT_A_DERIVED_READINESS_REQUIREMENT",
    "UNIMPLEMENTED_CAPABILITY_MUST_REMAIN_VISIBLE",
    "UNIVERSE_V1_ID",
    "UndeclaredScalar",
    "UndeclaredScalarReason",
    "UniverseManifest",
    "aggregate_universe",
    "annotations",
    "blocking_reason_for_gate",
    "build_declared_universe_v1",
    "capability_import_isolation_audit",
    "declaration_protocol_digest",
    "derive_arabic_state_certificate",
    "derive_citation_provenance_profile",
    "derive_composite_coverage",
    "derive_declaration_evidence",
    "derive_domain_coverage_profile",
    "derive_governance_indicators",
    "derive_readiness_gate_origin_profile",
    "licensable_gates",
    "measure_leaves",
    "rank_blockers",
]
