import Slge

-- المسلّماتُ المنطقيّة التي تستند إليها كلُّ مبرهنةٍ في السجلّ؛ يفحص CI أنها القياسيّة وحدها.
-- مبرهناتُ الـ116 (الغانم) بالإيداع المثبَّت في lakefile.toml:
#print axioms A116.mem_cells
#print axioms A116.cells_nodup
#print axioms A116.cells_length
#print axioms A116.cells_split
#print axioms A116.step_depends_only_on_sukun
#print axioms A116.run_fellOut
#print axioms A116.saturation_rungs
#print axioms A116.Sstar_closed
#print axioms A116.run_mem_Sstar
#print axioms A116.Sstar_complete
#print axioms A116.run_ne_fellOut_iff
#print axioms A116.run_eq_fellOut_iff
#print axioms A116.Fold.T_succ_succ
#print axioms A116.Fold.fold_lt
#print axioms A116.Fold.unfold_fold
#print axioms A116.Fold.unfold_spec
#print axioms A116.Fold.fold_injective
#print axioms A116.Fold.foldAny_injective
#print axioms A116.Fold.foldAny_surjective
#print axioms A116.admissible_iff_valid
#print axioms A116.run_ne_fellOut_iff_valid
#print axioms A116.cellFold_lt
#print axioms A116.cellFold_injective
#print axioms A116.cellFold_surjective
#print axioms A116.U_succ_succ
#print axioms A116.U_values
#print axioms A116.hamil_ladder
#print axioms A116.Fiber.decode_encode
#print axioms A116.Fiber.encode_injective
#print axioms A116.Fiber.decode_sound
#print axioms A116.Fiber.rank_lt
#print axioms A116.Fiber.fiber_length_le
#print axioms A116.Fiber.fiber_length_le_two_pow
#print axioms A116.Fiber.nodup_fin_length_le
#print axioms A116.Numbering.valid_zero_iff
#print axioms A116.Numbering.fold_zero_eq_digits
#print axioms A116.Numbering.foldAny_zero_closed
#print axioms A116.Numbering.bridgeCell_bridgeIndex
#print axioms A116.Numbering.bridgeIndex_bridgeCell
#print axioms A116.Numbering.orders_differ_only_in_two_rows
#print axioms A116.Numbering.atomNumber_closed
#print axioms A116.Numbering.atomNumber_injective
#print axioms A116.Numbering.atomNumber_surjective
#print axioms A116.Numbering.pair_injective
#print axioms A116.Numbering.pair_surjective
#print axioms A116.Numbering.pair_closed
#print axioms A116.Ishtiqaq.extract_fill_wf
#print axioms A116.Ishtiqaq.root_sublist_fill_wf
#print axioms A116.Ishtiqaq.fill_injective
#print axioms A116.Ishtiqaq.soundTemplates_wf
#print axioms A116.Ishtiqaq.form_alone_does_not_determine_root
#print axioms A116.Field112.field112_eq_cells112
#print axioms A116.Field112.hamzaRow_named
#print axioms A116.Field112.cells_eq_field112_append_hamza
#print axioms A116.Derivation.branching_nodes
#print axioms A116.Derivation.rows_stochastic
#print axioms A116.Derivation.stationary_unique
#print axioms A116.Derivation.share_of_I
#print axioms A116.Derivation.stationary_w
#print axioms A116.Ladder.run_depends_only_on_pattern
#print axioms A116.Ladder.U_eq_pow_mul_g
#print axioms A116.Ladder.pattern_count_fib
#print axioms A116.Ladder.admissible_patterns_3
#print axioms A116.Ladder.U3_by_pattern
#print axioms A116.Ladder.patterns_of_the_cited_words
#print axioms A116.Ladder.kana_and_inna_are_indistinguishable
#print axioms A116.Ladder.kana_is_not_kataba
#print axioms A116.Stages.parse_flat
#print axioms A116.Stages.flat_parse
#print axioms A116.Stages.flat_injective
#print axioms A116.Junction.admissible_map_carriers
#print axioms A116.Junction.admissible_prefix
#print axioms A116.Junction.admissible_append
#print axioms A116.Junction.U_by_patterns_upto_6
#print axioms A116.Junction.licensed_upto_4
#print axioms A116.Junction.burnside_3
#print axioms A116.Junction.burnside_4
#print axioms A116.Pause.mem_pats_iff
#print axioms A116.Pause.U_by_patterns
#print axioms A116.Pause.pause_admissible
#print axioms A116.Pause.pause_strictly_extends
#print axioms A116.Ternary.binary_is_continue
#print axioms A116.Ternary.continue_strictly_extends_binary
#print axioms A116.Ternary.continue_is_pause
#print axioms A116.Ternary.pause_strictly_extends_continue
#print axioms A116.Ternary.tamm_is_pause_only
#print axioms A116.Ternary.binary_is_blind_to_madd
#print axioms A116.Ternary.admissible_iff_admissibleB
#print axioms A116.Ternary.binOK_eq_admissibleB
#print axioms A116.Ternary.continueB_iff
#print axioms A116.Ternary.pauseB_iff
#print axioms A116.Recovery.edit_roundtrip
#print axioms A116.Recovery.shadda_restore
#print axioms A116.Recovery.tanwin_restore
#print axioms A116.Recovery.hamza_restore
#print axioms A116.Recovery.ilal_edit_restore
#print axioms A116.Recovery.no_seat_recovery_from_hamza_alone
#print axioms A116.Recovery.restoration_forces_fiber_separation
#print axioms A116.Recovery.compose_restoration
#print axioms A116.Residue.sukun_restore
#print axioms A116.Residue.fariqa_restore
#print axioms A116.Residue.tanwinAlif_restore
#print axioms A116.Residue.idgham_restore
#print axioms A116.Residue.chain_restore
#print axioms A116.Residue.residue_separates
#print axioms A116.Unicode.decode_encode
#print axioms A116.Unicode.encode_prefix_free
#print axioms A116.Unicode.decodeAll_encodeAll
#print axioms A116.Unicode.arabic_is_two_bytes
#print axioms A116.Unicode.markOrder_restore
#print axioms A116.Boundary.no_start_with_sukun
#print axioms A116.Boundary.pause_ends_with_sukun
#print axioms A116.Boundary.join_iff
#print axioms A116.Boundary.wasl_dropped_needs_moving_left
#print axioms A116.Boundary.pause_then_join_is_not_join
#print axioms A116.Ilal.admissible_replace_carrier
#print axioms A116.Ilal.vowelled_to_sukun_between_vowelled
#print axioms A116.Ilal.swap_sukun_vowel
#print axioms A116.Ilal.delete_sukun_after_vowelled
#print axioms A116.Ilal.two_sukun_not_admissible
#print axioms A116.Ilal.hadhf_ayn_forced
#print axioms A116.Ilal.qalb_ayn_restore
#print axioms A116.Ilal.naql_restore
#print axioms A116.Ilal.ibdal_restore
#print axioms A116.Ilal.qala_witness
#print axioms A116.Ilal.qultu_witness
#print axioms A116.Ilal.yaqulu_witness
#print axioms A116.Hamza.seat_initial_by_own
#print axioms A116.Hamza.seat_final_by_prev
#print axioms A116.Hamza.seat_after_madd_final_is_line
#print axioms A116.Hamza.seat_medial_strongest
#print axioms A116.Hamza.seat_depends_on_context
#print axioms A116.Hamza.qat_stays_when_joined
#print axioms A116.Hamza.prefix_hamza_admissible
-- مبرهناتُ SLGE:
#print axioms Slge.scells_length
#print axioms Slge.ofCell_toCell
#print axioms Slge.toCell_ofCell
#print axioms Slge.toCell_isSukun
#print axioms Slge.licensed_iff
#print axioms Slge.slgeFold_lt
#print axioms Slge.slgeFold_injective
#print axioms Slge.slgeFold_surjective
#print axioms Slge.count_eq_U
#print axioms Slge.Ghazali.ghazali_table
#print axioms Slge.Ghazali.barren_witnessed
#print axioms Slge.Ghazali.akhass_chain
#print axioms Slge.Ghazali.licence_makes_mafhum
#print axioms Slge.Rank.pathGrade_qati_iff
#print axioms Slge.Rank.no_promotion
#print axioms Slge.Rank.weigh_swap
#print axioms Slge.Rank.qati_never_loses
#print axioms Slge.Rank.mardud_iff
#print axioms Slge.Rank.tanaqud_iff
#print axioms Slge.Rank.taadul_iff
#print axioms Slge.Rank.specific_wins
#print axioms Slge.Rank.general_is_makhsus
#print axioms Slge.Rank.qati_general_yields_to_zanni_specific
#print axioms Slge.Rank.same_scope_is_weigh
#print axioms Slge.Rasm.read_write
#print axioms Slge.Rasm.write_injective
#print axioms Slge.Rasm.headOK_write
#print axioms Slge.Sequence.slgeUnfold_slgeFold
#print axioms Slge.Sequence.bitsToNat_natToBits
#print axioms Slge.Sequence.U_lt_two_pow_width
#print axioms Slge.Sequence.decodeWord_encodeWord
#print axioms Slge.Sequence.encodeWord_prefix_free
#print axioms Slge.Sequence.decode_encode
#print axioms Slge.Consistency.atomNumber_determines_fold
#print axioms Slge.Consistency.fold_determines_atomNumber
#print axioms Slge.Consistency.numbers_agree
#print axioms Slge.Categories.pronoun_sound
#print axioms Slge.Categories.pronoun_numbers_nodup
#print axioms Slge.Categories.sub_trans
#print axioms Slge.Grant.grant_iff_check
#print axioms Slge.Grant.no_grant_of_refused
#print axioms Slge.Grant.ladder_implies_base
#print axioms Slge.Grant.empty_ladder_grants_nothing
#print axioms Slge.Grant.mursam_sound
#print axioms Slge.Grant.mursam_refuses_initial_sukun
#print axioms Slge.Wazn.rootOf_fill
#print axioms Slge.Wazn.states_fill
#print axioms Slge.Wazn.licensed_fill_indep
#print axioms Slge.Wazn.awzan_wf
#print axioms Slge.Wazn.awzan_licensed
#print axioms Slge.Wazn.awzan_root
#print axioms Slge.Shabaka.wf_step
#print axioms Slge.Shabaka.wf_run
#print axioms Slge.Shabaka.edges_apply
#print axioms Slge.Shabaka.network_rooted
#print axioms Slge.Shabaka.run_edge_wf
#print axioms Slge.Khamsa.madd_matches_short
#print axioms Slge.Khamsa.caseOf_form
#print axioms Slge.Khamsa.form_injective_stem
#print axioms Slge.Khamsa.no_guess_for_plural
#print axioms Slge.Khamsa.khamsa_licensed
#print axioms Slge.Khamsa.khamsa_numbers_nodup
#print axioms Slge.Afal.glide_matches_before
#print axioms Slge.Afal.nasb_eq_jazm
#print axioms Slge.Afal.moodOf_raf
#print axioms Slge.Afal.moodOf_nasb
#print axioms Slge.Afal.pronounOf_form
#print axioms Slge.Afal.five_licensed
#print axioms Slge.Rawabit.particles_licensed
#print axioms Slge.Rawabit.proclitic_keeps_licence
#print axioms Slge.Rawabit.proclitics_one_vowelled_cell
#print axioms Slge.Rawabit.govern_jazm_afal
#print axioms Slge.Rawabit.govern_nasb_afal
#print axioms Slge.Rawabit.raf_not_governed_jazm
#print axioms Slge.Damair.iyya_is_carrier_plus_suffix
#print axioms Slge.Damair.na_raf_reads_sukun
#print axioms Slge.Damair.na_nasb_reads_vowel
#print axioms Slge.Damair.ta_person
#print axioms Slge.Damair.ta_after_vowel_not_subject
#print axioms Slge.Damair.attach_licensed
#print axioms Slge.Damair.witness_na_roles
#print axioms Slge.Damair.witness_ta_persons
#print axioms Slge.Damair.witness_iyya
#print axioms Slge.Damair.damair_licensed
#print axioms Slge.Damair.damair_nodup
#print axioms Slge.Damair.na_after_madd_not_raf
#print axioms Slge.Ishara.tanbih_licensed
#print axioms Slge.Ishara.bud_licensed
#print axioms Slge.Ishara.caseOf_dual
#print axioms Slge.Ishara.caseOf_dual_bud
#print axioms Slge.Ishara.nasb_eq_jarr_dual
#print axioms Slge.Ishara.forms_licensed
#print axioms Slge.Ishara.forms_nodup
#print axioms Slge.Ishara.duals_have_case
#print axioms Slge.Ishara.mabni_no_case
#print axioms Slge.Ishara.witnessed_subset
#print axioms Slge.Istifham.caseOf_ayy
#print axioms Slge.Istifham.ayy_differs_only_in_state
#print axioms Slge.Istifham.ayy_three_forms
#print axioms Slge.Istifham.mabni_single_form
#print axioms Slge.Istifham.madha_is_ma_dha
#print axioms Slge.Istifham.man_dha_junction
#print axioms Slge.Istifham.amman_is_am_man
#print axioms Slge.Istifham.ma_after_jarr
#print axioms Slge.Istifham.amma_is_an_ma_idgham
#print axioms Slge.Istifham.mimma_is_min_ma_idgham
#print axioms Slge.Istifham.idghamNM_length
#print axioms Slge.Istifham.hamza_prefix_licensed
#print axioms Slge.Istifham.forms_licensed
#print axioms Slge.Istifham.forms_nodup
#print axioms Slge.Nida.tanwin_never_bina
#print axioms Slge.Nida.damm_is_bina
#print axioms Slge.Nida.ya_junction
#print axioms Slge.Nida.nudba_not_binary_licensed
#print axioms Slge.Nida.particles_licensed
#print axioms Slge.Nida.particles_nodup
#print axioms Slge.Nida.witnesses_hukm
#print axioms Slge.Zuruf.hukm_qat
#print axioms Slge.Zuruf.hukm_mudaf
#print axioms Slge.Zuruf.hukm_jarr
#print axioms Slge.Zuruf.setLast_licensed
#print axioms Slge.Zuruf.forms_licensed
#print axioms Slge.Zuruf.forms_hukm
#print axioms Slge.Zuruf.constants_single
#print axioms Slge.Zuruf.haythu_always_cut
#print axioms Slge.Zaman.tanwin_vs_qat
#print axioms Slge.Zaman.hukm_rafTanwin
#print axioms Slge.Zaman.hukm_nasbTanwin
#print axioms Slge.Zaman.forms_licensed
#print axioms Slge.Zaman.forms_nodup
#print axioms Slge.Zaman.forms_hukm
#print axioms Slge.Zaman.constants_licensed
#print axioms Slge.Zaman.constants_states
#print axioms Slge.Zaman.al_amsu
#print axioms Slge.Adad.fem_is_masc_without_ta
#print axioms Slge.Adad.genderOf_masc
#print axioms Slge.Adad.genderOf_fem_forms
#print axioms Slge.Adad.six_ta_is_radical
#print axioms Slge.Adad.ten_single_opposes
#print axioms Slge.Adad.shin_law
#print axioms Slge.Adad.compound_both_fatha
#print axioms Slge.Adad.twelve_case
#print axioms Slge.Adad.uqud_case
#print axioms Slge.Adad.tamyiz_ranges
#print axioms Slge.Adad.forms_licensed
#print axioms Slge.Adad.forms_nodup
#print axioms Slge.Marifa.shamsi_licensed
#print axioms Slge.Marifa.al_licensed
#print axioms Slge.Marifa.hasAl_al
#print axioms Slge.Marifa.dropTanwin_licensed
#print axioms Slge.Marifa.idafa_no_tanwin
#print axioms Slge.Marifa.mudaf_is_marifa
#print axioms Slge.Marifa.mawsul_licensed
#print axioms Slge.Marifa.mawsul_nodup
#print axioms Slge.Marifa.mawsul_al
#print axioms Slge.Marifa.mawsul_dual_case
#print axioms Slge.Marifa.deposited_no_tanwin
#print axioms Slge.Marifa.man_looks_like_tanwin
#print axioms Slge.Sarf.jarr_eq_nasb
#print axioms Slge.Sarf.sarf_jarr_ne_nasb
#print axioms Slge.Sarf.al_jarr_kasra
#print axioms Slge.Sarf.idafa_jarr_kasra
#print axioms Slge.Sarf.onTemplate_fill
#print axioms Slge.Sarf.muntaha_wf
#print axioms Slge.Sarf.witnesses_illa
#print axioms Slge.Tawabi.compatible_symm
#print axioms Slge.Tawabi.follows_symm
#print axioms Slge.Tawabi.follows_refl
#print axioms Slge.Tawabi.four_markers_one_case
#print axioms Slge.Tawabi.follows_khamsa
#print axioms Slge.Tawabi.nasaq_in_rawabit
#print axioms Slge.Tawabi.tawkid_words_licensed
#print axioms Slge.Tawabi.tawkid_case
#print axioms Slge.Tawabi.caseClass_khamsa_raf
#print axioms Slge.Tawabi.khamsa_nasb_unread
#print axioms Slge.Tawabi.caseClass_uqud_raf
#print axioms Slge.Tawabi.caseClass_jam_muannath
#print axioms Slge.Nawasikh.inna_eq_swap_kana
#print axioms Slge.Nawasikh.kada_eq_kana
#print axioms Slge.Nawasikh.laJins_eq_inna
#print axioms Slge.Nawasikh.zanna_both_nasb
#print axioms Slge.Nawasikh.raf_licensed
#print axioms Slge.Nawasikh.nasb_licensed
#print axioms Slge.Nawasikh.setLast_eq_append
#print axioms Slge.Nawasikh.caseClass_of_last_damm
#print axioms Slge.Nawasikh.caseClass_raf
#print axioms Slge.Nawasikh.lastOf_setLast_carrier
#print axioms Slge.Nawasikh.caseClass_nasb
#print axioms Slge.Nawasikh.caseClass_nasb_tanwin
#print axioms Slge.Nawasikh.caseClass_raf_tanwin
#print axioms Slge.Nawasikh.caseClass_al_raf
#print axioms Slge.Nawasikh.caseClass_of_last_yin
#print axioms Slge.Nawasikh.uqud_nasb_compatible
#print axioms Slge.Nawasikh.no_tanwin_setLast
#print axioms Slge.Nawasikh.raf_no_tanwin
#print axioms Slge.Nawasikh.nasb_no_tanwin
#print axioms Slge.Nawasikh.hasAl_setLast
#print axioms Slge.Nawasikh.laJins_ism_no_tanwin
#print axioms Slge.Nawasikh.kana_licensed
#print axioms Slge.Nawasikh.kada_licensed
#print axioms Slge.Nawasikh.inna_licensed
#print axioms Slge.Nawasikh.zanna_licensed
#print axioms Slge.Nawasikh.counts
#print axioms Slge.Nawasikh.jaala_shared
#print axioms Slge.Nawasikh.inna_in_rawabit
#print axioms Slge.Nawasikh.laysa_la_ma_in_rawabit
#print axioms Slge.Nawasikh.kaffa_licensed
#print axioms Slge.Nawasikh.kaffa_forms
#print axioms Slge.Nawasikh.kaffa_forms_licensed
#print axioms Slge.Nawasikh.innama_kaffa_in_rawabit
#print axioms Slge.Nawasikh.kada_khabar_raf
#print axioms Slge.Nawasikh.an_licensed
#print axioms Slge.Nawasikh.an_in_rawabit
#print axioms Slge.Nawasikh.an_khabar_nasb
#print axioms Slge.Nawasikh.kana_inna_witness
#print axioms Slge.Nawasikh.la_rayb_witness
#print axioms Slge.Jazm.noAdj_append_two_sukun
#print axioms Slge.Jazm.sukun_licensed
#print axioms Slge.Jazm.hollow_forced
#print axioms Slge.Jazm.dropWeak_licensed
#print axioms Slge.Jazm.dropWeak_last
#print axioms Slge.Jazm.weak_witnesses
#print axioms Slge.Jazm.yaqulu_sukun_unlicensed
#print axioms Slge.Jazm.yaqul_licensed
#print axioms Slge.Jazm.waw_shared
#print axioms Slge.Jazm.marker_afal_jazm
#print axioms Slge.Jazm.afal_jazm_eq_nasb
#print axioms Slge.Jazm.marker_witnesses
#print axioms Slge.Jazm.tools_licensed
#print axioms Slge.Jazm.counts
#print axioms Slge.Jazm.amr_licensed
#print axioms Slge.Jazm.yunfiq_witness
#print axioms Slge.Jazm.shared_la_lamma
#print axioms Slge.Jazm.shared_istifham
#print axioms Slge.Jazm.ayy_declines
#print axioms Slge.Jazm.rawabit_jazm
#print axioms Slge.Jazm.two_verbs
#print axioms Slge.Mansubat.tamyiz_eq_hal
#print axioms Slge.Mansubat.nakira_reads_nasb
#print axioms Slge.Mansubat.nakira_has_tanwin
#print axioms Slge.Mansubat.nakira_licensed
#print axioms Slge.Mansubat.sorting_by_template
#print axioms Slge.Mansubat.derived_templates_wf
#print axioms Slge.Mansubat.derived_of_bare
#print axioms Slge.Mansubat.derived_witnesses
#print axioms Slge.Mansubat.adad_tamyiz_is_nakira
#print axioms Slge.Mansubat.tahwil_witness
#print axioms Slge.Mansubat.tamm_muthbat_reads_nasb
#print axioms Slge.Mansubat.badal_follows
#print axioms Slge.Mansubat.mufarragh_eq_role
#print axioms Slge.Mansubat.tools_licensed
#print axioms Slge.Mansubat.illa_ghayr_in_rawabit
#print axioms Slge.Mansubat.ghayr_idafa_jarr
#print axioms Slge.Mansubat.ghayr_takes_hukm
#print axioms Slge.Mansubat.ma_khala_nasb
#print axioms Slge.Mansubat.witnesses
#print axioms Slge.Mansubat.sukara_hal
#print axioms Slge.Majrurat.jarr_licensed
#print axioms Slge.Majrurat.caseClass_jarr
#print axioms Slge.Majrurat.caseClass_jarr_tanwin
#print axioms Slge.Majrurat.govern_jarr
#print axioms Slge.Majrurat.uqud_jarr_compatible
#print axioms Slge.Majrurat.caseClass_of_last_ayn
#print axioms Slge.Majrurat.dual_jarr_compatible
#print axioms Slge.Majrurat.khamsa_jarr_unread
#print axioms Slge.Majrurat.mamnu_jarr_reads_nasb
#print axioms Slge.Majrurat.masajid_witness
#print axioms Slge.Majrurat.harfs_licensed
#print axioms Slge.Majrurat.harfs_count
#print axioms Slge.Majrurat.proclitic_jarr_licensed
#print axioms Slge.Majrurat.harfs_in_rawabit
#print axioms Slge.Majrurat.qasam_witness
#print axioms Slge.Majrurat.rubba_nakira
#print axioms Slge.Majrurat.mudaf_no_tanwin
#print axioms Slge.Majrurat.mudaf_drops_nun
#print axioms Slge.Majrurat.muhandisu_witness
#print axioms Slge.Majrurat.lafziyya_by_template
#print axioms Slge.Majrurat.mudaf_marifa
#print axioms Slge.Majrurat.tabi_jarr_follows
#print axioms Slge.Majrurat.an_kasra_shared
#print axioms Slge.Majrurat.rajul_salih
#print axioms Slge.Wasl.no_initial_sukun
#print axioms Slge.Wasl.wasl_licenses
#print axioms Slge.Wasl.wasl_drops
#print axioms Slge.Wasl.wasl_after_sukun
#print axioms Slge.Wasl.qat_stays
#print axioms Slge.Wasl.quick_test
#print axioms Slge.Wasl.wasl_qat_cells_shared
#print axioms Slge.Wasl.templates_partition
#print axioms Slge.Wasl.templates_wf
#print axioms Slge.Wasl.ten_licensed
#print axioms Slge.Wasl.ten_count
#print axioms Slge.Wasl.ten_shape
#print axioms Slge.Wasl.illa_not_wasl
#print axioms Slge.Wasl.kind_witnesses
#print axioms Slge.Wasl.template_reads_what_cells_cannot
#print axioms Slge.Wasl.plural_qat
#print axioms Slge.Wasl.bism_witness
#print axioms Slge.Wasl.istifham_al_witness
#print axioms Slge.Wasl.istifhamVerb_licensed
#print axioms Slge.Ism.thulathi_ten
#print axioms Slge.Ism.thulathi_wf
#print axioms Slge.Ism.thulathi_licensed
#print axioms Slge.Ism.thulathi_read
#print axioms Slge.Ism.witnesses_read
#print axioms Slge.Ism.rubai_shapes
#print axioms Slge.Ism.khumasi_shapes
#print axioms Slge.Ism.tasghir_licensed
#print axioms Slge.Ism.tasghir_read
#print axioms Slge.Ism.tasghir_witnesses
#print axioms Slge.Ism.nisba_licensed
#print axioms Slge.Ism.nisba_read
#print axioms Slge.Ism.nisba_witnesses
#print axioms Slge.Ism.arid_bina
#print axioms Slge.Ism.lazim_deposited
#print axioms Slge.Fil.abwab_six
#print axioms Slge.Fil.bab_wf
#print axioms Slge.Fil.bab_licensed
#print axioms Slge.Fil.bab_read
#print axioms Slge.Fil.bab_witnesses
#print axioms Slge.Fil.bab3_condition_witness
#print axioms Slge.Fil.mazid_counts
#print axioms Slge.Fil.amr_of_pres
#print axioms Slge.Fil.amr_ifalla_unlicensed
#print axioms Slge.Fil.rubai_shapes
#print axioms Slge.Fil.root_is_ternary
#print axioms Slge.Fil.qalb_witness
#print axioms Slge.Fil.naql_witness
#print axioms Slge.Fil.qalb_licensed
#print axioms Slge.Fil.naql_licensed
#print axioms Slge.Fil.hadhf_witness
#print axioms Slge.Fil.ibdal_map_isSukun
#print axioms Slge.Fil.ibdal_licensed
#print axioms Slge.Fil.ibdal_witnesses
#print axioms Slge.Fil.idgham_licensed
#print axioms Slge.Fil.qalb_pastT
#print axioms Slge.Fil.idgham_pastT
#print axioms Slge.Fil.readers_witnesses
#print axioms Slge.Fil.kada_eleven
#print axioms Slge.Huruf.counts
#print axioms Slge.Huruf.table_licensed
#print axioms Slge.Huruf.no_tanwin
#print axioms Slge.Huruf.proclitics_keep_licence
#print axioms Slge.Huruf.shared_cells
#print axioms Slge.Huruf.amal_is_operation
#print axioms Slge.Huruf.rawabit_agrees
#print axioms Slge.Huruf.sawfa_witness
#print axioms Slge.Jumla.nominal_reads_raf
#print axioms Slge.Jumla.nominal_licensed
#print axioms Slge.Jumla.pronoun_is_damir
#print axioms Slge.Jumla.raf_is_ism
#print axioms Slge.Jumla.kinds_witnesses
#print axioms Slge.Jumla.swap_swap
#print axioms Slge.Jumla.lam_licensed
#print axioms Slge.Jumla.order_swap
#print axioms Slge.Jumla.order_lam
#print axioms Slge.Jumla.lam_refuses_khabar_first
#print axioms Slge.Jumla.order_witnesses
#print axioms Slge.Jumla.number_taNith
#print axioms Slge.Jumla.gender_taNith
#print axioms Slge.Jumla.number_ops
#print axioms Slge.Jumla.gender_jamF
#print axioms Slge.Jumla.agree_ops
#print axioms Slge.Jumla.suffix_licensed
#print axioms Slge.Jumla.ops_licensed
#print axioms Slge.Jumla.agree_witnesses
#print axioms Slge.Jumla.rabit_repeat
#print axioms Slge.Jumla.rabit_witnesses
#print axioms Slge.Jumla.lawla_witness
#print axioms Slge.Filiyya.past_endings
#print axioms Slge.Filiyya.past_licensed
#print axioms Slge.Filiyya.amr_ends_like_jazm
#print axioms Slge.Filiyya.fail_reads_raf
#print axioms Slge.Filiyya.subjectSuffixes_from_table
#print axioms Slge.Filiyya.attached_subject
#print axioms Slge.Filiyya.attached_object
#print axioms Slge.Filiyya.order_swap
#print axioms Slge.Filiyya.attached_subject_first
#print axioms Slge.Filiyya.attached_object_first
#print axioms Slge.Filiyya.order_witnesses
#print axioms Slge.Filiyya.majhul_fill
#print axioms Slge.Filiyya.majhul_witnesses
#print axioms Slge.Filiyya.naib_eq_fail
#print axioms Slge.Filiyya.naib_witnesses
#print axioms Slge.Filiyya.maful_reads_nasb
#print axioms Slge.Filiyya.zarf_reads_nasb
#print axioms Slge.Filiyya.sorting_masdar_hal
#print axioms Slge.Filiyya.maiyya_licensed
#print axioms Slge.Filiyya.tafaala_is_ataf
#print axioms Slge.Filiyya.mutlaq_shares_root
#print axioms Slge.Shibh.jarr_majrur_reads_jarr
#print axioms Slge.Shibh.jarr_majrur_licensed
#print axioms Slge.Shibh.kind_witnesses
#print axioms Slge.Shibh.setLast_setLast
#print axioms Slge.Shibh.zaid_restores
#print axioms Slge.Shibh.zaid_witness
#print axioms Slge.Shibh.masjid_not_zarf
#print axioms Slge.Shibh.anchor_witnesses
#print axioms Slge.Shibh.mahall_after_mawsul
#print axioms Slge.Shibh.mahall_after_nakira
#print axioms Slge.Shibh.mahall_after_al_raf
#print axioms Slge.Shibh.mahall_witnesses
#print axioms Slge.Shibh.kawn_reads
#print axioms Slge.Nisab.isnad_one_operation
#print axioms Slge.Nisab.isnad_reads_raf
#print axioms Slge.Nisab.taqyid_nasb
#print axioms Slge.Nisab.taqyid_jarr
#print axioms Slge.Nisab.naat_follows
#print axioms Slge.Nisab.taqyid_raf_only_by_following
#print axioms Slge.Nisab.contains_refl
#print axioms Slge.Nisab.contains_trans
#print axioms Slge.Nisab.contains_antisymm
#print axioms Slge.Nisab.slots_ordered
#print axioms Slge.Nisab.map_carrier_fill
#print axioms Slge.Nisab.form_contains_root
#print axioms Slge.Nisab.chains_end_at_root
#print axioms Slge.Nisab.species_distinct
#print axioms Slge.Nisab.nisba_witnesses
#print axioms Slge.Talil.liajlih_reads_nasb
#print axioms Slge.Talil.fadla_witnesses
#print axioms Slge.Talil.two_forms_same_word
#print axioms Slge.Talil.tools_licensed
#print axioms Slge.Talil.tools_count
#print axioms Slge.Talil.tools_in_rawabit
#print axioms Slge.Talil.li_anna_eq_inna
#print axioms Slge.Talil.talil_never_raf
#print axioms Slge.Talil.min_ajli_jarr
#print axioms Slge.Talil.derives_irrefl_all
#print axioms Slge.Talil.derives_dist_all
#print axioms Slge.Talil.derives_trans_all
#print axioms Slge.Talil.derives_irrefl
#print axioms Slge.Talil.derives_dist
#print axioms Slge.Talil.derives_trans
#print axioms Slge.Talil.derives_asymm
#print axioms Slge.Talil.root_causes_all
#print axioms Slge.Talil.nearer_works
#print axioms Slge.Talil.first_takes_pronoun
#print axioms Slge.Talil.tanazu_witness
#print axioms Slge.Talil.fronting_keeps_nasb
#print axioms Slge.Talil.talil_witnesses
#print axioms Slge.Maqam.suffixShakhs_covers
#print axioms Slge.Maqam.present_heads_ya
#print axioms Slge.Maqam.present_templates_wf
#print axioms Slge.Maqam.withPrefix_fill
#print axioms Slge.Maqam.present_prefix_reads_person
#print axioms Slge.Maqam.hadir_wujub
#print axioms Slge.Maqam.ghaib_jawaz
#print axioms Slge.Maqam.zahir_only_ghaib
#print axioms Slge.Maqam.zahir_not_hadir
#print axioms Slge.Maqam.mustatir_has_no_cell
#print axioms Slge.Maqam.shakhs_witnesses
#print axioms Slge.Maqam.zuhur_witnesses
#print axioms Slge.Maqam.detached_all_read
#print axioms Slge.Maqam.detached_mem
#print axioms Slge.Maqam.tawkid_needs_both
#print axioms Slge.Maqam.tawkid_witnesses
#print axioms Slge.Maqam.aid_forces_maful_first
#print axioms Slge.Jiha.states_of_onTemplate
#print axioms Slge.Jiha.sigha_states_disjoint
#print axioms Slge.Jiha.withPrefix_states
#print axioms Slge.Jiha.past_templates_wf
#print axioms Slge.Jiha.amr_templates_wf
#print axioms Slge.Jiha.not_on_other_class
#print axioms Slge.Jiha.onTemplateRoot_fill
#print axioms Slge.Jiha.isPresent_prefix
#print axioms Slge.Jiha.sigha_of_fill
#print axioms Slge.Jiha.amr_fill_last
#print axioms Slge.Jiha.amr_is_mukhatab
#print axioms Slge.Jiha.ghaib_amr_by_lam
#print axioms Slge.Jiha.shift_only_present
#print axioms Slge.Jiha.past_not_shifted
#print axioms Slge.Jiha.sa_restores
#print axioms Slge.Jiha.lam_restores
#print axioms Slge.Jiha.sa_licensed
#print axioms Slge.Jiha.shifts_in_rawabit
#print axioms Slge.Jiha.jiha_witnesses
#print axioms Slge.Naat.naatOk_refl
#print axioms Slge.Naat.naatOk_symm
#print axioms Slge.Naat.naatOk_case
#print axioms Slge.Naat.naatOk_definite
#print axioms Slge.Naat.naatOk_agree
#print axioms Slge.Naat.non_matching_case_blocked
#print axioms Slge.Naat.non_matching_definite_blocked
#print axioms Slge.Naat.khabar_not_naat
#print axioms Slge.Naat.hasAl_setLast_tanwin
#print axioms Slge.Naat.nakira_pair_two_coordinates
#print axioms Slge.Naat.hal_requires_marifa
#print axioms Slge.Naat.naat_after_nakira
#print axioms Slge.Naat.naat_witnesses
#print axioms Slge.Uslub.truth_iff_khabar
#print axioms Slge.Uslub.tools_licensed
#print axioms Slge.Uslub.tools_count
#print axioms Slge.Uslub.tools_in_rawabit
#print axioms Slge.Uslub.setLast_id
#print axioms Slge.Uslub.amr_is_insha
#print axioms Slge.Uslub.present_fill_last
#print axioms Slge.Uslub.map_state_setLast
#print axioms Slge.Uslub.sukun_present_not_past
#print axioms Slge.Uslub.la_splits_by_last_state
#print axioms Slge.Uslub.nahy_only_present
#print axioms Slge.Uslub.ma_afala_splits_by_next_case
#print axioms Slge.Uslub.uslub_witnesses
#print axioms Slge.Talab.ismFil_licensed
#print axioms Slge.Talab.ismFil_count
#print axioms Slge.Talab.four_forms_witnesses
#print axioms Slge.Talab.lam_reaches_every_person
#print axioms Slge.Talab.lam_amr_jazm
#print axioms Slge.Talab.lam_amr_licensed
#print axioms Slge.Talab.la_before_amr_stays_amr
#print axioms Slge.Talab.nahy_requires_la
#print axioms Slge.Talab.amr_never_reads_nahy
#print axioms Slge.Kulli.universal_in_particulars
#print axioms Slge.Kulli.particulars_off_templates
#print axioms Slge.Kulli.juzi_by_table
#print axioms Slge.Kulli.aradi_hadath_disjoint
#print axioms Slge.Kulli.masdar_templates_wf
#print axioms Slge.Kulli.masdar_states_disjoint
#print axioms Slge.Kulli.masdar_no_sigha
#print axioms Slge.Kulli.masdar_not_shifted
#print axioms Slge.Kulli.kulli_witnesses
#print axioms Slge.Wad.wad_injective
#print axioms Slge.Wad.sense_of_fill
#print axioms Slge.Wad.duplicate_templates
#print axioms Slge.Wad.mayCollide_sound
#print axioms Slge.Wad.mem_collisionPairs
#print axioms Slge.Wad.homonymy_is_tabled
#print axioms Slge.Wad.collision_pairs_eq
#print axioms Slge.Wad.collision_pairs_split
#print axioms Slge.Wad.mizan_unaided
#print axioms Slge.Wad.mizan_senses
#print axioms Slge.Wad.taraduf_same_root
#print axioms Slge.Wad.masdar_forms_distinct
#print axioms Slge.Wad.wad_witnesses
#print axioms Slge.Wad.intishar_two_roots
#print axioms Slge.Tabayun.shareMadda_iff
#print axioms Slge.Tabayun.shareMadda_symm
#print axioms Slge.Tabayun.tabayun_symm
#print axioms Slge.Tabayun.shareMadda_self
#print axioms Slge.Tabayun.tabayun_irrefl
#print axioms Slge.Tabayun.isolated_count
#print axioms Slge.Tabayun.templ_wf
#print axioms Slge.Tabayun.mawadd_fill_isolated
#print axioms Slge.Tabayun.tabayun_of_isolated
#print axioms Slge.Tabayun.fill_functional
#print axioms Slge.Tabayun.rel_witnesses
#print axioms Slge.Tabayun.seven_not_exhaustive
