import Slge

-- المسلّماتُ المنطقيّة التي تستند إليها كلُّ مبرهنةٍ في السجلّ؛ يفحص CI أنها القياسيّة وحدها.
#print axioms Slge.scells_length
#print axioms Slge.ofCell_toCell
#print axioms Slge.toCell_ofCell
#print axioms Slge.toCell_isSukun
#print axioms Slge.licensed_iff
#print axioms Slge.slgeFold_injective
#print axioms Slge.slgeFold_surjective
#print axioms Slge.count_eq_U
#print axioms Slge.Ghazali.ghazali_table
#print axioms Slge.Ghazali.barren_witnessed
#print axioms Slge.Ghazali.akhass_chain
#print axioms Slge.Ghazali.licence_makes_mafhum
#print axioms Slge.Rank.pathGrade_qati_iff
#print axioms Slge.Rank.no_promotion
#print axioms Slge.Rank.weigh_swap
#print axioms Slge.Rank.qati_never_loses
#print axioms Slge.Rank.mardud_iff
#print axioms Slge.Rank.tanaqud_iff
#print axioms Slge.Rank.taadul_iff
#print axioms Slge.Rank.specific_wins
#print axioms Slge.Rank.general_is_makhsus
#print axioms Slge.Rank.qati_general_yields_to_zanni_specific
#print axioms Slge.Rank.same_scope_is_weigh
#print axioms Slge.Rasm.read_write
#print axioms Slge.Rasm.write_injective
#print axioms Slge.Rasm.headOK_write
#print axioms Slge.Sequence.slgeUnfold_slgeFold
#print axioms Slge.Sequence.bitsToNat_natToBits
#print axioms Slge.Sequence.U_lt_two_pow_width
#print axioms Slge.Sequence.decodeWord_encodeWord
#print axioms Slge.Sequence.encodeWord_prefix_free
#print axioms Slge.Sequence.decode_encode
#print axioms Slge.Consistency.atomNumber_determines_fold
#print axioms Slge.Consistency.fold_determines_atomNumber
#print axioms Slge.Consistency.numbers_agree
#print axioms Slge.Categories.pronoun_sound
#print axioms Slge.Categories.pronoun_numbers_nodup
#print axioms Slge.Categories.sub_trans
#print axioms Slge.Grant.grant_iff_check
#print axioms Slge.Grant.no_grant_of_refused
#print axioms Slge.Grant.ladder_implies_base
#print axioms Slge.Grant.empty_ladder_grants_nothing
#print axioms Slge.Grant.mursam_sound
#print axioms Slge.Grant.mursam_refuses_initial_sukun
#print axioms Slge.Wazn.rootOf_fill
#print axioms Slge.Wazn.states_fill
#print axioms Slge.Wazn.licensed_fill_indep
#print axioms Slge.Wazn.awzan_wf
#print axioms Slge.Wazn.awzan_licensed
#print axioms Slge.Wazn.awzan_root
#print axioms Slge.Shabaka.wf_step
#print axioms Slge.Shabaka.wf_run
#print axioms Slge.Shabaka.edges_apply
#print axioms Slge.Shabaka.network_rooted
#print axioms Slge.Shabaka.run_edge_wf
#print axioms Slge.Khamsa.madd_matches_short
#print axioms Slge.Khamsa.caseOf_form
#print axioms Slge.Khamsa.form_injective_stem
#print axioms Slge.Khamsa.no_guess_for_plural
#print axioms Slge.Khamsa.khamsa_licensed
#print axioms Slge.Khamsa.khamsa_numbers_nodup
