import Slge.Bridge
import Slge.Ghazali
import Slge.Rank
import Slge.Rasm
import Slge.Sequence
import Slge.Consistency
import Slge.Categories
import Slge.Grant
import Slge.Wazn
import Slge.Shabaka
import Slge.Khamsa
