import Slge.Bridge
import Slge.Ghazali
import Slge.Rank
import Slge.Rasm
import Slge.Sequence
import Slge.Consistency
import Slge.Categories
import Slge.Grant
import Slge.Wazn
import Slge.Shabaka
import Slge.Khamsa
import Slge.Afal
import Slge.Rawabit
import Slge.Damair
import Slge.Ishara
import Slge.Istifham
import Slge.Nida
import Slge.Zuruf
import Slge.Zaman
import Slge.Adad
import Slge.Marifa
import Slge.Sarf
import Slge.Tawabi
import Slge.Nawasikh
import Slge.Jazm
import Slge.Mansubat
import Slge.Majrurat
import Slge.Wasl
import Slge.Ism
import Slge.Fil
import Slge.Huruf
import Slge.Jumla
import Slge.Filiyya
import Slge.Shibh
import Slge.Nisab
import Slge.Talil
import Slge.Maqam
import Slge.Jiha
import Slge.Naat
import Slge.Uslub
import Slge.Talab
import Slge.Kulli
import Slge.Wad
import Slge.Tabayun
import Slge.Madd
import Slge.Ilal
import Slge.Jidh
import Slge.MaqayisTable
import Slge.Maqayis
import Slge.AbniyaTable
import Slge.Abniya
import Slge.Adawat
import Slge.WujudTable
import Slge.Wujud
import Slge.MaaniTable
import Slge.Maani
import Slge.MukhassasTable
import Slge.Mukhassas
import Slge.ZawaidTable
import Slge.Zawaid
import Slge.MakharijTable
import Slge.Makharij
