import Slge.Bridge
import Slge.Ghazali
import Slge.Rank
import Slge.Rasm
import Slge.Sequence
import Slge.Consistency
import Slge.Categories
import Slge.Grant
import Slge.Wazn
import Slge.Shabaka
import Slge.Khamsa
import Slge.Afal
import Slge.Rawabit
import Slge.Damair
import Slge.Ishara
import Slge.Istifham
import Slge.Nida
import Slge.Zuruf
import Slge.Zaman
import Slge.Adad
import Slge.Marifa
import Slge.Sarf
import Slge.Tawabi
