"""حدُّ التأسيس: النواةُ مكتوبةٌ يدويًّا، ولا تستورد ما تولِّده."""

from __future__ import annotations

import ast
from pathlib import Path

_SOURCE_ROOT = Path(__file__).resolve().parents[2] / "src" / "alghanem"


def _imported_modules(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    modules: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            prefix = "." * node.level
            modules.append(prefix + (node.module or ""))
        elif isinstance(node, ast.Import):
            modules.extend(alias.name for alias in node.names)
    return modules


def test_the_metaalgebra_core_never_imports_the_generation_package() -> None:
    for path in sorted((_SOURCE_ROOT / "metaalgebra").glob("*.py")):
        for module in _imported_modules(path):
            assert "realization" not in module or module in {
                ".realization",
                "realization",
            }, (path.name, module)
            assert "generated" not in module, (path.name, module)


def test_the_metaalgebra_realization_module_is_the_model_not_the_generator() -> None:
    path = _SOURCE_ROOT / "metaalgebra" / "realization.py"
    modules = _imported_modules(path)
    assert all(not module.startswith("alghanem.realization") for module in modules)
    assert all("python_backend" not in module for module in modules)


def test_nothing_outside_the_generated_tree_imports_the_generated_tree() -> None:
    for path in sorted(_SOURCE_ROOT.rglob("*.py")):
        if "generated" in path.parts:
            continue
        for module in _imported_modules(path):
            assert "realization.generated" not in module, (path.name, module)
            assert not module.endswith(".generated"), (path.name, module)


def test_the_generator_package_is_not_itself_generated() -> None:
    for path in sorted((_SOURCE_ROOT / "realization").glob("*.py")):
        text = path.read_text(encoding="utf-8")
        assert "GENERATED BY G_py — DO NOT EDIT BY HAND" not in text.splitlines()[0:1]


def test_the_generation_package_depends_on_the_core_and_not_the_reverse() -> None:
    generation_imports = [
        module
        for path in sorted((_SOURCE_ROOT / "realization").glob("*.py"))
        for module in _imported_modules(path)
    ]
    assert any("metaalgebra" in module for module in generation_imports)
    core_imports = [
        module
        for path in sorted((_SOURCE_ROOT / "metaalgebra").glob("*.py"))
        for module in _imported_modules(path)
    ]
    assert not any("python_backend" in module for module in core_imports)
